import {
  CircuitBoard,
  Cpu,
  Factory,
  FileText,
  Layers,
  Newspaper,
  Radio,
  ShieldCheck,
} from 'lucide-react';

import type { SearchResultItem, SearchSitePack } from './types';

function item(partial: SearchResultItem): SearchResultItem {
  return partial;
}

/**
 * Catalog hrefs match Amkor Sitecore routes from get_all_pages_by_site (hyphenated).
 * Facet keys are Amkor-specific; Quanex/Pillsbury packs are unchanged.
 */
const catalog: SearchResultItem[] = [
  item({
    id: 'amk-packaging',
    kbId: 'HUB',
    title: 'Packaging',
    subtitle: 'IC packaging portfolio',
    description:
      'Amkor packaging platforms across laminate, leadframe, power, wafer level, memory, MEMS, and system-in-package — built for high-volume semiconductor manufacturing.',
    href: '/Packaging',
    lob: 'packaging',
    perils: ['laminate', 'leadframe', 'power', 'wafer', 'sip'],
    topics: ['ai', 'automotive', 'computing'],
    searchBuckets: ['packaging', 'osat', 'bga', 'sip'],
    breadcrumb: ['Packaging'],
    matchTerms: ['packaging', 'osat', 'ic package', 'assembly'],
    isNew: true,
  }),
  item({
    id: 'amk-fcbga',
    kbId: 'PKG',
    title: 'FCBGA',
    subtitle: 'Flip chip ball grid array',
    description:
      'Flip chip BGA packaging for high-performance computing and networking silicon that needs dense interconnect, thermal headroom, and proven high-volume assembly.',
    href: '/Packaging/Laminate/FCBGA',
    lob: 'packaging',
    perils: ['laminate'],
    topics: ['ai', 'computing', 'communications'],
    searchBuckets: ['packaging', 'bga', 'flipchip', 'laminate'],
    breadcrumb: ['Packaging', 'Laminate', 'FCBGA'],
    matchTerms: ['fcbga', 'flip chip bga', 'ball grid array', 'hpc'],
  }),
  item({
    id: 'amk-fccsp',
    kbId: 'PKG',
    title: 'fcCSP',
    subtitle: 'Flip chip chip-scale package',
    description:
      'Flip chip CSP for mobile, compute, and communications devices that need a compact footprint with high-density interconnect.',
    href: '/Packaging/Laminate/fcCSP',
    lob: 'packaging',
    perils: ['laminate'],
    topics: ['communications', 'computing', 'consumer'],
    searchBuckets: ['packaging', 'csp', 'flipchip', 'laminate'],
    breadcrumb: ['Packaging', 'Laminate', 'fcCSP'],
    matchTerms: ['fccsp', 'flip chip csp', 'chip scale'],
  }),
  item({
    id: 'amk-flipstack',
    kbId: 'PKG',
    title: 'FlipStack CSP',
    subtitle: 'Stacked laminate CSP',
    description:
      'Stacked CSP packaging for memory-plus-logic combinations in a compact laminate form factor.',
    href: '/Packaging/Laminate/FlipStack-CSP',
    lob: 'packaging',
    perils: ['laminate', 'sip'],
    topics: ['computing', 'communications'],
    searchBuckets: ['packaging', 'csp', 'sip', 'laminate'],
    breadcrumb: ['Packaging', 'Laminate', 'FlipStack CSP'],
    matchTerms: ['flipstack', 'stacked csp', 'pop', 'memory stack'],
  }),
  item({
    id: 'amk-laminate',
    kbId: 'HUB',
    title: 'Laminate',
    subtitle: 'Laminate package family',
    description:
      'Laminate packaging including CABGA/FBGA, FCBGA, fcCSP, stacked CSP, and related BGA platforms.',
    href: '/Packaging/Laminate',
    lob: 'packaging',
    perils: ['laminate'],
    topics: ['ai', 'computing', 'communications'],
    searchBuckets: ['packaging', 'laminate', 'bga'],
    breadcrumb: ['Packaging', 'Laminate'],
    matchTerms: ['laminate', 'bga', 'fbga', 'cabga'],
  }),
  item({
    id: 'amk-mlf',
    kbId: 'PKG',
    title: 'MicroLeadFrame',
    subtitle: 'Leadframe QFN platform',
    description:
      'MicroLeadFrame QFN-style packaging for analog, RF, and power-adjacent devices that need a compact, thermally efficient leadframe.',
    href: '/Packaging/Leadframe/MicroLeadFrame',
    lob: 'packaging',
    perils: ['leadframe'],
    topics: ['automotive', 'industrial', 'communications'],
    searchBuckets: ['packaging', 'qfn', 'leadframe'],
    breadcrumb: ['Packaging', 'Leadframe', 'MicroLeadFrame'],
    matchTerms: ['microleadframe', 'mlf', 'qfn', 'leadframe'],
  }),
  item({
    id: 'amk-leadframe',
    kbId: 'HUB',
    title: 'Leadframe',
    subtitle: 'Leadframe package family',
    description:
      'Leadframe packaging including LQFP, TQFP, SOIC, TSSOP, fcMLF, and MicroLeadFrame platforms.',
    href: '/Packaging/Leadframe',
    lob: 'packaging',
    perils: ['leadframe'],
    topics: ['automotive', 'industrial', 'consumer'],
    searchBuckets: ['packaging', 'leadframe', 'qfn'],
    breadcrumb: ['Packaging', 'Leadframe'],
    matchTerms: ['leadframe', 'lqfp', 'tqfp', 'soic', 'tssop'],
  }),
  item({
    id: 'amk-power',
    kbId: 'HUB',
    title: 'Power',
    subtitle: 'Power packaging',
    description:
      'Power discrete and module packaging — D2PAK, DPAK, PowerCSP, PQFN, TOLL, and related high-current platforms for automotive and industrial.',
    href: '/Packaging/Power',
    lob: 'packaging',
    perils: ['power'],
    topics: ['automotive', 'industrial'],
    searchBuckets: ['packaging', 'power', 'automotive'],
    breadcrumb: ['Packaging', 'Power'],
    matchTerms: ['power package', 'mosfet', 'discrete', 'd2pak', 'dpak'],
    isNew: true,
  }),
  item({
    id: 'amk-powercsp',
    kbId: 'PKG',
    title: 'PowerCSP',
    subtitle: 'Chip-scale power package',
    description:
      'PowerCSP for compact, thermally efficient power devices used in automotive, industrial, and computing power stages.',
    href: '/Packaging/Power/PowerCSP',
    lob: 'packaging',
    perils: ['power'],
    topics: ['automotive', 'computing', 'industrial'],
    searchBuckets: ['packaging', 'power', 'csp'],
    breadcrumb: ['Packaging', 'Power', 'PowerCSP'],
    matchTerms: ['powercsp', 'power csp', 'power discrete'],
  }),
  item({
    id: 'amk-d2pak',
    kbId: 'PKG',
    title: 'D2PAK (TO-263)',
    subtitle: 'Power discrete package',
    description:
      'D2PAK / TO-263 power packaging for high-current MOSFETs and similar discrete devices.',
    href: '/Packaging/Power/D2PAK-TO-263',
    lob: 'packaging',
    perils: ['power'],
    topics: ['automotive', 'industrial'],
    searchBuckets: ['packaging', 'power', 'automotive'],
    breadcrumb: ['Packaging', 'Power', 'D2PAK (TO-263)'],
    matchTerms: ['d2pak', 'to-263', 'to263', 'power mosfet'],
  }),
  item({
    id: 'amk-wafer',
    kbId: 'HUB',
    title: 'Wafer Level',
    subtitle: 'WLCSP, WLFO, WLSiP',
    description:
      'Wafer-level packaging including WLCSP, WLFO/WLCSP+, and WLSiP/WL3D for compact consumer, IoT, and mobile silicon.',
    href: '/Packaging/Wafer-Level',
    lob: 'packaging',
    perils: ['wafer'],
    topics: ['consumer', 'iot', 'communications'],
    searchBuckets: ['packaging', 'wlcsp', 'wafer'],
    breadcrumb: ['Packaging', 'Wafer Level'],
    matchTerms: ['wafer level', 'wlcsp', 'wlfo', 'wlsip', 'fan-out'],
  }),
  item({
    id: 'amk-wlcsp',
    kbId: 'PKG',
    title: 'WLCSP',
    subtitle: 'Wafer-level chip-scale package',
    description: 'Wafer-level CSP for space-constrained consumer, IoT, and mobile devices.',
    href: '/Packaging/Wafer-Level/WLCSP',
    lob: 'packaging',
    perils: ['wafer'],
    topics: ['consumer', 'iot', 'communications'],
    searchBuckets: ['packaging', 'wlcsp', 'wafer', 'csp'],
    breadcrumb: ['Packaging', 'Wafer Level', 'WLCSP'],
    matchTerms: ['wlcsp', 'wafer level csp', 'chip scale'],
  }),
  item({
    id: 'amk-sip',
    kbId: 'PKG',
    title: 'System in Package (SiP)',
    subtitle: 'Heterogeneous integration',
    description:
      'System-in-package solutions that combine multiple die, passives, and interconnect in a single module for RF, IoT, and compact systems.',
    href: '/Packaging/System-in-Package-SiP',
    lob: 'packaging',
    perils: ['sip'],
    topics: ['communications', 'iot', 'consumer'],
    searchBuckets: ['packaging', 'sip', 'module'],
    breadcrumb: ['Packaging', 'System in Package (SiP)'],
    matchTerms: ['sip', 'system in package', 'module', 'heterogeneous'],
    isNew: true,
  }),
  item({
    id: 'amk-memory',
    kbId: 'HUB',
    title: 'Memory',
    subtitle: 'Memory packaging',
    description:
      'Memory packaging platforms for stacked and high-bandwidth memory used in compute and mobile applications.',
    href: '/Packaging/Memory',
    lob: 'packaging',
    perils: ['sip'],
    topics: ['computing', 'ai', 'communications'],
    searchBuckets: ['packaging', 'memory', 'sip'],
    breadcrumb: ['Packaging', 'Memory'],
    matchTerms: ['memory package', 'hbm', 'dram', 'nand'],
  }),
  item({
    id: 'amk-mems',
    kbId: 'HUB',
    title: 'MEMS and Sensors',
    subtitle: 'Sensor packaging',
    description:
      'Packaging for MEMS and optical sensors used in automotive, industrial, and consumer devices.',
    href: '/Packaging/MEMS-and-Sensors',
    lob: 'packaging',
    perils: ['wafer'],
    topics: ['automotive', 'industrial', 'consumer'],
    searchBuckets: ['packaging', 'mems', 'sensor'],
    breadcrumb: ['Packaging', 'MEMS and Sensors'],
    matchTerms: ['mems', 'sensor', 'optical sensor'],
  }),
  item({
    id: 'amk-technology',
    kbId: 'HUB',
    title: 'Technology',
    subtitle: 'Advanced packaging technology',
    description:
      'Amkor interconnect and advanced packaging technologies — flip chip, copper pillar, 2.5D/3D TSV, SWIFT, S-SWIFT, and S-Connect.',
    href: '/Technology',
    lob: 'technology',
    perils: ['interconnect'],
    topics: ['ai', 'computing'],
    searchBuckets: ['technology', 'interconnect', 'advanced', '2.5d'],
    breadcrumb: ['Technology'],
    matchTerms: ['advanced packaging', 'interconnect', 'technology'],
    isNew: true,
  }),
  item({
    id: 'amk-sconnect',
    kbId: 'TECH',
    title: 'S-Connect',
    subtitle: 'Bridge die interposer',
    description:
      'S-Connect is Amkor’s bridge-die interposer solution for high-bandwidth die-to-die connections in AI and high-performance compute packages.',
    href: '/Technology/S-Connect',
    lob: 'technology',
    perils: ['interconnect'],
    topics: ['ai', 'computing'],
    searchBuckets: ['technology', 'interconnect', '2.5d', 'ai'],
    breadcrumb: ['Technology', 'S-Connect'],
    matchTerms: ['s-connect', 'sconnect', 'interposer', 'bridge die', 'die-to-die'],
    isNew: true,
  }),
  item({
    id: 'amk-sswift',
    kbId: 'TECH',
    title: 'S-SWIFT',
    subtitle: 'Advanced SWIFT platform',
    description:
      'S-SWIFT extends Amkor SWIFT fan-out technology for high-density, high-bandwidth packages used in AI infrastructure and advanced compute.',
    href: '/Technology/S-SWIFT',
    lob: 'technology',
    perils: ['interconnect', 'wafer'],
    topics: ['ai', 'computing'],
    searchBuckets: ['technology', 'swift', 'fanout', 'ai'],
    breadcrumb: ['Technology', 'S-SWIFT'],
    matchTerms: ['s-swift', 'sswift', 'fan-out', 'rdt'],
  }),
  item({
    id: 'amk-swift',
    kbId: 'TECH',
    title: 'SWIFT',
    subtitle: 'Silicon wafer integrated fan-out',
    description:
      'SWIFT fan-out packaging for high-density interconnect without a conventional laminate substrate.',
    href: '/Technology/SWIFT',
    lob: 'technology',
    perils: ['interconnect', 'wafer'],
    topics: ['ai', 'computing', 'communications'],
    searchBuckets: ['technology', 'swift', 'fanout'],
    breadcrumb: ['Technology', 'SWIFT'],
    matchTerms: ['swift', 'fan-out', 'wlfo', 'integrated fan-out'],
  }),
  item({
    id: 'amk-tsv',
    kbId: 'TECH',
    title: '2.5D / 3D TSV',
    subtitle: 'Through-silicon via integration',
    description:
      '2.5D and 3D TSV integration for high-bandwidth memory and logic stacking in AI and HPC packages.',
    href: '/Technology/2-5D-3D-TSV',
    lob: 'technology',
    perils: ['interconnect'],
    topics: ['ai', 'computing'],
    searchBuckets: ['technology', '2.5d', '3d', 'tsv'],
    breadcrumb: ['Technology', '2.5D/3D TSV'],
    matchTerms: ['2.5d', '3d', 'tsv', 'through silicon via', 'hbm'],
  }),
  item({
    id: 'amk-stacked-die',
    kbId: 'TECH',
    title: '3D Stacked Die',
    subtitle: 'Die stacking',
    description:
      '3D stacked-die assembly for memory and logic combinations that need vertical integration.',
    href: '/Technology/3D-Stacked-Die',
    lob: 'technology',
    perils: ['interconnect', 'sip'],
    topics: ['computing', 'ai'],
    searchBuckets: ['technology', '3d', 'sip'],
    breadcrumb: ['Technology', '3D Stacked Die'],
    matchTerms: ['stacked die', '3d stack', 'die stacking'],
  }),
  item({
    id: 'amk-flipchip',
    kbId: 'TECH',
    title: 'Flip Chip',
    subtitle: 'Flip chip interconnect',
    description:
      'Flip chip interconnect used across FCBGA, fcCSP, and advanced packages for high I/O and electrical performance.',
    href: '/Technology/Flip-Chip',
    lob: 'technology',
    perils: ['interconnect', 'laminate'],
    topics: ['computing', 'communications', 'ai'],
    searchBuckets: ['technology', 'flipchip', 'interconnect'],
    breadcrumb: ['Technology', 'Flip Chip'],
    matchTerms: ['flip chip', 'c4', 'bump', 'fcbga'],
  }),
  item({
    id: 'amk-copper-pillar',
    kbId: 'TECH',
    title: 'Copper Pillar',
    subtitle: 'Fine-pitch bumping',
    description:
      'Copper pillar bumping for fine-pitch flip chip interconnect in advanced laminate and wafer-level packages.',
    href: '/Technology/Copper-Pillar',
    lob: 'technology',
    perils: ['interconnect'],
    topics: ['computing', 'ai'],
    searchBuckets: ['technology', 'interconnect', 'flipchip'],
    breadcrumb: ['Technology', 'Copper Pillar'],
    matchTerms: ['copper pillar', 'cupillar', 'fine pitch', 'bumping'],
  }),
  item({
    id: 'amk-pop',
    kbId: 'TECH',
    title: 'Package-on-Package',
    subtitle: 'PoP stacking',
    description:
      'Package-on-package stacking for memory-on-logic configurations in mobile and compact compute.',
    href: '/Technology/Package-on-Package',
    lob: 'technology',
    perils: ['sip'],
    topics: ['communications', 'computing'],
    searchBuckets: ['technology', 'sip', 'memory'],
    breadcrumb: ['Technology', 'Package-on-Package'],
    matchTerms: ['package on package', 'pop', 'memory on logic'],
  }),
  item({
    id: 'amk-test',
    kbId: 'HUB',
    title: 'Test Services',
    subtitle: 'Wafer and package test',
    description:
      'Amkor test services spanning wafer test, final test, and related backend test for advanced packaging programs — including the new U.S. advanced packaging and test facility.',
    href: '/Test-Services',
    lob: 'test',
    perils: ['test'],
    topics: ['ai', 'automotive', 'computing'],
    searchBuckets: ['test', 'probe', 'finaltest', 'arizona'],
    breadcrumb: ['Test Services'],
    matchTerms: ['test services', 'final test', 'wafer test', 'ate', 'peoria', 'arizona'],
    isNew: true,
  }),
  item({
    id: 'amk-services',
    kbId: 'HUB',
    title: 'Services',
    subtitle: 'Design, characterization, bumping',
    description:
      'Engineering services that sit alongside packaging and test — design, package characterization, and wafer bumping.',
    href: '/Services',
    lob: 'service',
    perils: ['design'],
    topics: ['computing', 'ai'],
    searchBuckets: ['service', 'design', 'bumping'],
    breadcrumb: ['Services'],
    matchTerms: ['engineering services', 'design services', 'characterization'],
  }),
  item({
    id: 'amk-design',
    kbId: 'SVC',
    title: 'Design Services',
    subtitle: 'Package design',
    description:
      'Package design support for substrate, interconnect, and thermal/mechanical requirements before high-volume production.',
    href: '/Services/Design-Services',
    lob: 'service',
    perils: ['design'],
    topics: ['computing', 'ai', 'automotive'],
    searchBuckets: ['service', 'design'],
    breadcrumb: ['Services', 'Design Services'],
    matchTerms: ['package design', 'substrate design', 'si pi'],
  }),
  item({
    id: 'amk-characterization',
    kbId: 'SVC',
    title: 'Package Characterization',
    subtitle: 'Electrical, thermal, mechanical',
    description:
      'Characterization services that quantify electrical, thermal, and mechanical package performance for qualification and customer design-in.',
    href: '/Services/Package-Characterization',
    lob: 'service',
    perils: ['design', 'test'],
    topics: ['automotive', 'computing'],
    searchBuckets: ['service', 'test', 'design'],
    breadcrumb: ['Services', 'Package Characterization'],
    matchTerms: ['characterization', 'thermal', 'mechanical', 'electrical'],
  }),
  item({
    id: 'amk-bumping',
    kbId: 'SVC',
    title: 'Wafer Bumping',
    subtitle: 'Front-end of assembly',
    description:
      'Wafer bumping including copper pillar and related bump processes that feed flip chip and advanced packaging lines.',
    href: '/Services/Wafer-Bumping',
    lob: 'service',
    perils: ['design', 'interconnect'],
    topics: ['computing', 'ai'],
    searchBuckets: ['service', 'bumping', 'flipchip'],
    breadcrumb: ['Services', 'Wafer Bumping'],
    matchTerms: ['wafer bumping', 'bump', 'copper pillar bump'],
  }),
  item({
    id: 'amk-applications',
    kbId: 'HUB',
    title: 'Applications',
    subtitle: 'Markets we serve',
    description:
      'How Amkor packaging and test map to end markets — AI, automotive, communications, computing, consumer, industrial, IoT, and networking.',
    href: '/Applications',
    lob: 'application',
    perils: ['laminate', 'power', 'sip'],
    topics: ['ai', 'automotive', 'computing'],
    searchBuckets: ['application', 'market', 'ai'],
    breadcrumb: ['Applications'],
    matchTerms: ['applications', 'end market', 'use case'],
  }),
  item({
    id: 'amk-ai',
    kbId: 'MKT',
    title: 'Artificial Intelligence',
    subtitle: 'AI and machine learning packaging',
    description:
      'Advanced packaging for AI accelerators and high-bandwidth memory — 2.5D/3D, S-Connect, SWIFT/S-SWIFT, and FCBGA platforms used in AI infrastructure.',
    href: '/Applications/Artificial-Intelligence',
    lob: 'application',
    perils: ['interconnect', 'laminate'],
    topics: ['ai', 'computing'],
    searchBuckets: ['ai', 'application', '2.5d', 'hbm'],
    breadcrumb: ['Applications', 'Artificial Intelligence'],
    matchTerms: ['artificial intelligence', 'machine learning', 'accelerator', 'gpu', 'hbm'],
    isNew: true,
  }),
  item({
    id: 'amk-auto',
    kbId: 'MKT',
    title: 'Automotive',
    subtitle: 'Automotive packaging and test',
    description:
      'Automotive-grade packaging and test for ADAS, electrification, and in-vehicle compute — including power packages and qualified assembly flows.',
    href: '/Applications/Automotive',
    lob: 'application',
    perils: ['power', 'leadframe'],
    topics: ['automotive'],
    searchBuckets: ['automotive', 'application', 'power', 'adas'],
    breadcrumb: ['Applications', 'Automotive'],
    matchTerms: ['automotive', 'adas', 'ev', 'aec', 'in-vehicle'],
  }),
  item({
    id: 'amk-comms',
    kbId: 'MKT',
    title: 'Communications',
    subtitle: 'RF and connectivity',
    description:
      'Packaging for communications silicon — RF, 5G, and connectivity modules including SiP and compact laminate platforms.',
    href: '/Applications/Communications',
    lob: 'application',
    perils: ['sip', 'laminate'],
    topics: ['communications'],
    searchBuckets: ['application', 'rf', '5g', 'sip'],
    breadcrumb: ['Applications', 'Communications'],
    matchTerms: ['communications', '5g', 'rf', 'wireless'],
  }),
  item({
    id: 'amk-compute',
    kbId: 'MKT',
    title: 'Computing',
    subtitle: 'HPC and client compute',
    description:
      'Packaging for high-performance and client computing — FCBGA, advanced interconnect, and related test.',
    href: '/Applications/Computing',
    lob: 'application',
    perils: ['laminate', 'interconnect'],
    topics: ['computing', 'ai'],
    searchBuckets: ['application', 'computing', 'hpc'],
    breadcrumb: ['Applications', 'Computing'],
    matchTerms: ['computing', 'hpc', 'cpu', 'client'],
  }),
  item({
    id: 'amk-iot',
    kbId: 'MKT',
    title: 'Internet of Things',
    subtitle: 'IoT packaging',
    description:
      'Compact packaging for IoT devices — wafer-level, SiP, and leadframe platforms for connected sensors and edge nodes.',
    href: '/Applications/Internet-of-Things',
    lob: 'application',
    perils: ['wafer', 'sip'],
    topics: ['iot'],
    searchBuckets: ['application', 'iot', 'wlcsp'],
    breadcrumb: ['Applications', 'Internet of Things'],
    matchTerms: ['iot', 'internet of things', 'edge', 'sensor node'],
  }),
  item({
    id: 'amk-networking',
    kbId: 'MKT',
    title: 'Networking',
    subtitle: 'Networking silicon',
    description:
      'Packaging for networking and datacenter connectivity silicon that needs high I/O and thermal performance.',
    href: '/Applications/Networking',
    lob: 'application',
    perils: ['laminate', 'interconnect'],
    topics: ['communications', 'computing'],
    searchBuckets: ['application', 'networking', 'datacenter'],
    breadcrumb: ['Applications', 'Networking'],
    matchTerms: ['networking', 'switch', 'datacenter', 'ethernet'],
  }),
  item({
    id: 'amk-quality',
    kbId: 'PAGE',
    title: 'Quality',
    subtitle: 'Quality management',
    description:
      'Amkor quality systems, factory certifications, and manufacturing excellence across the global OSAT footprint.',
    href: '/Quality',
    lob: 'quality',
    perils: ['test'],
    topics: ['automotive', 'customer'],
    searchBuckets: ['quality', 'iso', 'cert'],
    breadcrumb: ['Quality'],
    matchTerms: ['quality', 'iso', 'iatf', 'certification', 'reliability'],
  }),
  item({
    id: 'amk-about',
    kbId: 'PAGE',
    title: 'Amkor Overview',
    subtitle: 'Who we are',
    description:
      'Amkor Technology is a leading OSAT partner for advanced packaging and test, with a global manufacturing footprint including a new U.S. advanced packaging and test facility.',
    href: '/About-Us/Amkor-Overview',
    lob: 'company',
    perils: ['test'],
    topics: ['customer', 'talent'],
    searchBuckets: ['company', 'osat', 'arizona'],
    breadcrumb: ['About Us', 'Amkor Overview'],
    matchTerms: ['about amkor', 'osat', 'company overview', 'who we are'],
  }),
  item({
    id: 'amk-smart-mfg',
    kbId: 'PAGE',
    title: 'Smart Manufacturing (I4.0)',
    subtitle: 'Industry 4.0 factories',
    description:
      'How Amkor applies Industry 4.0 — automation, data, and smart manufacturing — across packaging and test operations.',
    href: '/About-Us/Smart-Manufacturing-I40',
    lob: 'company',
    perils: ['test'],
    topics: ['industrial', 'customer'],
    searchBuckets: ['company', 'i40', 'manufacturing'],
    breadcrumb: ['About Us', 'Smart Manufacturing (I4.0)'],
    matchTerms: ['smart manufacturing', 'industry 4.0', 'i4.0', 'automation'],
  }),
  item({
    id: 'amk-careers',
    kbId: 'PAGE',
    title: 'Careers',
    subtitle: 'Join Amkor',
    description:
      'Engineering, operations, and corporate careers across Amkor sites — including the United States, Korea, Portugal, Vietnam, and other manufacturing locations.',
    href: '/About-Us/Careers',
    lob: 'company',
    perils: ['test'],
    topics: ['talent'],
    searchBuckets: ['career', 'jobs', 'arizona'],
    breadcrumb: ['About Us', 'Careers'],
    matchTerms: ['careers', 'jobs', 'hiring', 'openings'],
  }),
  item({
    id: 'amk-careers-us',
    kbId: 'PAGE',
    title: 'Careers — United States',
    subtitle: 'U.S. opportunities',
    description:
      'U.S. career opportunities, including roles supporting Amkor’s Arizona advanced packaging and test campus.',
    href: '/About-Us/Careers/United-States',
    lob: 'company',
    perils: ['test'],
    topics: ['talent'],
    searchBuckets: ['career', 'jobs', 'arizona'],
    breadcrumb: ['About Us', 'Careers', 'United States'],
    matchTerms: ['united states jobs', 'arizona jobs', 'peoria careers'],
  }),
  item({
    id: 'amk-contact',
    kbId: 'PAGE',
    title: 'Contact Us',
    subtitle: 'Talk to Amkor',
    description: 'Contact Amkor for packaging, test, samples, and customer support.',
    href: '/About-Us/Contact-Us',
    lob: 'company',
    perils: ['test'],
    topics: ['customer'],
    searchBuckets: ['contact', 'sales'],
    breadcrumb: ['About Us', 'Contact Us'],
    matchTerms: ['contact', 'sales', 'quote', 'representative'],
  }),
  item({
    id: 'amk-docs',
    kbId: 'PAGE',
    title: 'Document Library',
    subtitle: 'Datasheets and collateral',
    description:
      'Customer-facing document library for package datasheets, application notes, and related collateral.',
    href: '/About-Us/Customer-Center/Document-Library',
    lob: 'company',
    perils: ['design'],
    topics: ['customer'],
    searchBuckets: ['docs', 'datasheet', 'customer'],
    breadcrumb: ['About Us', 'Customer Center', 'Document Library'],
    matchTerms: ['document library', 'datasheet', 'application note', 'pdf'],
  }),
  item({
    id: 'amk-samples',
    kbId: 'PAGE',
    title: 'Amkor Mechanical Samples',
    subtitle: 'Package samples',
    description: 'Mechanical samples for package evaluation before committing a production flow.',
    href: '/About-Us/Customer-Center/Amkor-Mechanical-Samples',
    lob: 'company',
    perils: ['design'],
    topics: ['customer'],
    searchBuckets: ['customer', 'sample'],
    breadcrumb: ['About Us', 'Customer Center', 'Amkor Mechanical Samples'],
    matchTerms: ['mechanical samples', 'dummy package', 'sample kit'],
  }),
  item({
    id: 'amk-blog',
    kbId: 'NEWS',
    title: 'Blog',
    subtitle: 'Amkor news and stories',
    description:
      'Amkor blog covering advanced packaging, the U.S. factory, talent, and industry events.',
    href: '/About-Us/News/Blog',
    lob: 'news',
    perils: ['test'],
    topics: ['customer', 'talent'],
    searchBuckets: ['news', 'blog'],
    breadcrumb: ['About Us', 'News', 'Blog'],
    matchTerms: ['blog', 'news', 'stories'],
  }),
  item({
    id: 'amk-peoria',
    kbId: 'NEWS',
    title: 'Amkor Peoria — Number One Deal in North America',
    subtitle: 'U.S. advanced packaging campus',
    description:
      'Coverage of Amkor’s Peoria, Arizona advanced packaging and test investment — the U.S. manufacturing story for OSAT capacity close to AI and automotive customers.',
    href: '/About-Us/News/Blog/Amkor-Peoria-Number-One-Deal-North-America',
    lob: 'news',
    perils: ['test'],
    topics: ['ai', 'talent', 'customer'],
    searchBuckets: ['arizona', 'peoria', 'news', 'test'],
    breadcrumb: ['About Us', 'News', 'Blog', 'Amkor Peoria Number One Deal North America'],
    matchTerms: ['peoria', 'arizona', 'us factory', 'chips act', 'advanced packaging facility'],
    isNew: true,
  }),
  item({
    id: 'amk-nvidia',
    kbId: 'NEWS',
    title: 'Strategic Partnership with NVIDIA',
    subtitle: 'Press release',
    description:
      'Amkor announces a strategic partnership with NVIDIA around advanced packaging capacity for AI infrastructure.',
    href: '/About-Us/News/Press-Releases/Amkor-Technology-Announces-Strategic-Partnership-with-NVIDIA',
    lob: 'news',
    perils: ['interconnect'],
    topics: ['ai', 'computing', 'customer'],
    searchBuckets: ['ai', 'news', 'nvidia'],
    breadcrumb: ['About Us', 'News', 'Press Releases', 'Strategic Partnership with NVIDIA'],
    matchTerms: ['nvidia', 'partnership', 'ai infrastructure', 'press release'],
  }),
];

export const amkorSearchPack: SearchSitePack = {
  siteName: 'amkor',
  brandName: 'Amkor',
  catalog,
  facetLabels: {
    lob: {
      packaging: 'Packaging',
      technology: 'Technology',
      test: 'Test services',
      service: 'Engineering services',
      application: 'Applications',
      company: 'Company',
      news: 'News',
      quality: 'Quality',
    },
    peril: {
      laminate: 'Laminate / BGA',
      leadframe: 'Leadframe',
      power: 'Power',
      wafer: 'Wafer level',
      sip: 'System in package',
      interconnect: 'Advanced interconnect',
      test: 'Test',
      design: 'Design & characterization',
    },
    topic: {
      ai: 'Artificial intelligence',
      automotive: 'Automotive',
      communications: 'Communications',
      computing: 'Computing',
      consumer: 'Consumer',
      industrial: 'Industrial',
      iot: 'IoT',
      customer: 'Customers',
      talent: 'Careers',
    },
  },
  bucketSynonyms: {
    packaging: ['packaging', 'package', 'osat', 'assembly'],
    osat: ['osat', 'outsourced assembly', 'foundry partner'],
    bga: ['bga', 'ball grid', 'fcbga', 'fbga', 'cabga'],
    csp: ['csp', 'chip scale', 'fccsp', 'wlcsp'],
    sip: ['sip', 'system in package', 'module', 'heterogeneous'],
    laminate: ['laminate', 'substrate', 'bga'],
    leadframe: ['leadframe', 'qfn', 'mlf', 'lqfp', 'soic'],
    qfn: ['qfn', 'microleadframe', 'mlf', 'fcmlf'],
    power: ['power', 'mosfet', 'd2pak', 'dpak', 'powercsp', 'discrete'],
    wafer: ['wafer level', 'wlcsp', 'wlfo', 'fan-out', 'fanout'],
    wlcsp: ['wlcsp', 'wafer level csp'],
    mems: ['mems', 'sensor', 'optical sensor'],
    memory: ['memory', 'hbm', 'dram', 'nand'],
    technology: ['technology', 'interconnect', 'advanced packaging'],
    interconnect: ['interconnect', 'interposer', 'bridge', 'pillar'],
    advanced: ['advanced packaging', 'heterogeneous', '2.5d', '3d'],
    '2.5d': ['2.5d', '2.5 d', 'interposer', 'hbm'],
    '3d': ['3d', 'stacked die', 'tsv'],
    tsv: ['tsv', 'through silicon', 'through-silicon'],
    swift: ['swift', 's-swift', 'fan-out', 'wlfo'],
    fanout: ['fan-out', 'fanout', 'swift', 'wlfo'],
    ai: ['ai', 'artificial intelligence', 'machine learning', 'accelerator', 'gpu'],
    hbm: ['hbm', 'high bandwidth memory'],
    flipchip: ['flip chip', 'flipchip', 'c4'],
    bumping: ['bump', 'bumping', 'copper pillar'],
    test: ['test', 'ate', 'probe', 'final test', 'wafer test'],
    probe: ['probe', 'wafer sort', 'cp test'],
    finaltest: ['final test', 'package test'],
    arizona: ['arizona', 'peoria', 'phoenix', 'us factory', 'united states factory'],
    peoria: ['peoria', 'arizona campus'],
    service: ['service', 'design', 'characterization'],
    design: ['design', 'substrate design', 'package design'],
    application: ['application', 'market', 'end market'],
    market: ['automotive', 'ai', 'communications'],
    rf: ['rf', '5g', 'wireless'],
    '5g': ['5g', 'mmwave', 'rf'],
    automotive: ['automotive', 'adas', 'ev', 'aec', 'vehicle'],
    adas: ['adas', 'autonomous', 'ad as'],
    computing: ['computing', 'hpc', 'cpu', 'datacenter'],
    hpc: ['hpc', 'high performance', 'accelerator'],
    networking: ['networking', 'switch', 'ethernet'],
    datacenter: ['datacenter', 'data center', 'cloud'],
    iot: ['iot', 'internet of things', 'edge'],
    module: ['module', 'sip', 'rf module'],
    quality: ['quality', 'iso', 'iatf', 'reliability'],
    iso: ['iso', 'certification'],
    cert: ['cert', 'certificate', 'iatf'],
    company: ['company', 'about', 'amkor'],
    i40: ['industry 4.0', 'i4.0', 'smart manufacturing'],
    manufacturing: ['manufacturing', 'factory', 'fabless partner'],
    career: ['career', 'job', 'jobs', 'hiring'],
    jobs: ['jobs', 'openings', 'careers'],
    contact: ['contact', 'sales', 'quote'],
    sales: ['sales', 'representative'],
    docs: ['document', 'datasheet', 'library'],
    datasheet: ['datasheet', 'spec', 'pdf'],
    customer: ['customer', 'b2b', 'samples'],
    sample: ['sample', 'mechanical sample'],
    news: ['news', 'blog', 'press'],
    blog: ['blog', 'article'],
    nvidia: ['nvidia', 'gpu', 'ai partner'],
  },
  popularSearches: [
    'S-Connect for AI accelerators',
    'FCBGA advanced packaging',
    'Automotive power packages',
    'Wafer-level WLCSP',
    'Test services in Arizona',
    'System in Package',
  ],
  insightRules: [
    {
      id: 'ai-packaging',
      matchAny: [
        ['s-connect'],
        ['sconnect'],
        ['s-swift'],
        ['swift'],
        ['2.5d'],
        ['3d', 'tsv'],
        ['hbm'],
        ['artificial', 'intelligence'],
        ['ai', 'packag'],
        ['nvidia'],
        ['accelerator'],
      ],
      insight: {
        id: 'ai-amkor-ai',
        headline: 'Start with the interconnect, then the package',
        answer:
          'Amkor AI stories usually land on S-Connect (bridge-die interposer) and SWIFT / S-SWIFT fan-out, then FCBGA or 2.5D/3D TSV when the customer needs HBM-class bandwidth. Test Services and the Arizona campus close the “where it is built” question.',
        bullets: [
          'Open S-Connect for die-to-die / interposer language.',
          'Use SWIFT or S-SWIFT when the demo needs fan-out density.',
          'Pair with Artificial Intelligence under Applications and Test Services for the production path.',
        ],
        citations: [
          {
            title: 'S-Connect',
            href: '/Technology/S-Connect',
            kbId: 'TECH',
            excerpt: 'Bridge-die interposer for high-bandwidth AI packages.',
          },
          {
            title: 'Artificial Intelligence',
            href: '/Applications/Artificial-Intelligence',
            kbId: 'MKT',
            excerpt: 'How Amkor packaging maps to AI infrastructure.',
          },
        ],
        learnMoreHref: '/Technology',
        learnMoreLabel: 'Browse advanced packaging technology',
      },
    },
    {
      id: 'automotive-power',
      matchAny: [['automotive'], ['adas'], ['power', 'pack'], ['d2pak'], ['powercsp'], ['ev']],
      insight: {
        id: 'ai-amkor-auto',
        headline: 'Power package first, then the qualified flow',
        answer:
          'Automotive demos should open Power (D2PAK, PowerCSP) and the Automotive applications page. Quality and Test Services support the AEC / factory-certification conversation without leaving the Amkor tree.',
        bullets: [
          'Power hub covers D2PAK, DPAK, PowerCSP, and related discretes.',
          'Automotive applications page frames ADAS and electrification.',
          'Quality is the certification follow-on.',
        ],
        citations: [
          {
            title: 'Power',
            href: '/Packaging/Power',
            kbId: 'HUB',
            excerpt: 'Power discrete and module packaging.',
          },
          {
            title: 'Automotive',
            href: '/Applications/Automotive',
            kbId: 'MKT',
            excerpt: 'Automotive packaging and test.',
          },
        ],
        learnMoreHref: '/Applications/Automotive',
        learnMoreLabel: 'Open automotive applications',
      },
    },
    {
      id: 'wafer-level',
      matchAny: [['wlcsp'], ['wafer', 'level'], ['wlfo'], ['fan-out'], ['fanout']],
      insight: {
        id: 'ai-amkor-wlcsp',
        headline: 'Wafer-level when the board budget is tight',
        answer:
          'Consumer, IoT, and mobile compactness stories belong on Wafer Level — WLCSP, then WLFO / WLSiP when the customer needs fan-out or 3D wafer-level integration. SWIFT is the technology-page counterpart.',
        bullets: [
          'WLCSP is the default chip-scale answer.',
          'Wafer Level hub compares WLCSP, WLFO, and WLSiP.',
        ],
        citations: [
          {
            title: 'WLCSP',
            href: '/Packaging/Wafer-Level/WLCSP',
            kbId: 'PKG',
            excerpt: 'Wafer-level chip-scale package.',
          },
          {
            title: 'Wafer Level',
            href: '/Packaging/Wafer-Level',
            kbId: 'HUB',
            excerpt: 'WLCSP, WLFO, and WLSiP family.',
          },
        ],
        learnMoreHref: '/Packaging/Wafer-Level',
        learnMoreLabel: 'Browse wafer-level packaging',
      },
    },
    {
      id: 'test-arizona',
      matchAny: [
        ['test'],
        ['arizona'],
        ['peoria'],
        ['ate'],
        ['final', 'test'],
        ['us', 'factory'],
        ['united', 'states', 'packag'],
      ],
      insight: {
        id: 'ai-amkor-test',
        headline: 'Test is the U.S. capacity story',
        answer:
          'When the visitor asks about Arizona, Peoria, or “where do you test,” lead with Test Services, then the Peoria blog item and U.S. careers. Packaging hubs still matter — they are what the line is built to run.',
        bullets: [
          'Test Services is the operational landing page.',
          'Peoria coverage explains the North America investment.',
          'U.S. Careers supports the talent follow-on.',
        ],
        citations: [
          {
            title: 'Test Services',
            href: '/Test-Services',
            kbId: 'HUB',
            excerpt: 'Wafer and package test, including U.S. capacity.',
          },
          {
            title: 'Amkor Peoria — Number One Deal in North America',
            href: '/About-Us/News/Blog/Amkor-Peoria-Number-One-Deal-North-America',
            kbId: 'NEWS',
            excerpt: 'U.S. advanced packaging and test campus.',
          },
        ],
        learnMoreHref: '/Test-Services',
        learnMoreLabel: 'Open test services',
      },
    },
    {
      id: 'sip-modules',
      matchAny: [['sip'], ['system', 'in', 'package'], ['module'], ['rf'], ['5g']],
      insight: {
        id: 'ai-amkor-sip',
        headline: 'SiP when it is more than one die',
        answer:
          'RF, IoT, and compact-system stories should open System in Package, then Communications or IoT applications. FlipStack CSP and Package-on-Package cover memory-plus-logic stacking when the customer is not asking for a full SiP module.',
        bullets: [
          'SiP is the heterogeneous-integration hub.',
          'Communications and IoT pages frame the end market.',
        ],
        citations: [
          {
            title: 'System in Package (SiP)',
            href: '/Packaging/System-in-Package-SiP',
            kbId: 'PKG',
            excerpt: 'Multi-die modules and heterogeneous integration.',
          },
          {
            title: 'Communications',
            href: '/Applications/Communications',
            kbId: 'MKT',
            excerpt: 'RF and connectivity packaging.',
          },
        ],
        learnMoreHref: '/Packaging/System-in-Package-SiP',
        learnMoreLabel: 'Open system-in-package',
      },
    },
  ],
  copy: {
    kicker: 'Amkor search',
    headingEmpty: 'Find packaging, technology & test',
    intro:
      'Search the way semiconductor customers buy: start with the package or the market (AI, automotive, wafer-level), then land on a technology page, test services, or the factory story.',
    placeholder: 'Search FCBGA, S-Connect, WLCSP, automotive power…',
    emptyHint: 'Try “S-Connect,” “FCBGA,” or “test services in Arizona.”',
    resultsHint: ' — try a starter search or name a package family',
    aiHeading: 'Application-aware guidance',
    citationsHeading: 'Recommended pages',
    facetLob: 'Content type',
    facetPeril: 'Solution area',
    facetTopic: 'Market',
    tips: [
      {
        title: 'Search the package or the market',
        body: 'Use “FCBGA,” “WLCSP,” or “automotive power” to land on the right family.',
      },
      {
        title: 'Technology sits next to the product',
        body: 'S-Connect, SWIFT, and 2.5D/3D TSV explain how advanced packages are built.',
      },
      {
        title: 'Filter by who you serve',
        body: 'AI, automotive, and IoT facets keep a demo from mixing the wrong catalog.',
      },
    ],
  },
  ctaByLob: {
    packaging: 'View packaging',
    technology: 'View technology',
    test: 'Open test services',
    service: 'Explore services',
    application: 'View application',
    company: 'Open page',
    news: 'Read story',
    quality: 'View quality',
  },
  defaultCta: 'Open page',
  iconByLob: {
    packaging: Layers,
    technology: Cpu,
    test: CircuitBoard,
    service: Factory,
    application: Radio,
    company: FileText,
    news: Newspaper,
    quality: ShieldCheck,
  },
  featuredLob: 'packaging',
  enableDemoPersona: false,
};
