import { CalendarDays, FileText, Newspaper, Store } from 'lucide-react';

import type { SearchResultItem, SearchSitePack } from './types';

function item(partial: SearchResultItem): SearchResultItem {
  return partial;
}

const IMG = {
  a: '/Content-Card-AI-for-Good-Farmland.jpg',
  b: '/Content-Card-Copilot-Commercial.jpg',
  c: '/Content-Card-Microsoft-Teams-Commercial-Meeting.jpg',
  d: '/Content-Card-Refurbished-Devices-Surface-Xbox.jpg',
  e: '/Content-Card-Surface-Pro-AI-11Ed-Platinum-x86-001-COMMR.jpg',
} as const;

/**
 * Atlanta Apparel catalog — exhibitor directory + market events.
 * Hrefs match the atlanta-apparel content tree (Visit/Events, Visit/Registration).
 */
const catalog: SearchResultItem[] = [
  item({
    id: 'aa-exh-anna-ober',
    kbId: 'EXH',
    title: 'Anna Ober & Co., LLC',
    subtitle: '5 Lines Shown',
    description:
      'Jewelry and accessories lines on the show floor — including September birthstone pieces buyers can shop year-round in the digital showroom.',
    href: '/Discover',
    lob: 'exhibitor',
    perils: ['jewelry', 'accessories'],
    topics: ['atlanta', 'showroom'],
    searchBuckets: ['september', 'jewelry', 'exhibitor', 'showroom'],
    breadcrumb: ['Exhibitor Directory', 'Anna Ober & Co.'],
    matchTerms: ['anna ober', 'september', 'sapphire', 'cz bezel', 'jewelry', 'directory'],
    booth: 'B3 2-1809',
    linesShown: 5,
    matchingProducts: [
      { title: 'CZ Bezel Pendant - Sapphire (September)', imageSrc: IMG.a },
      { title: 'CZ Bezel Pendant - Sapphire (September)', imageSrc: IMG.b },
      { title: 'CZ Bezel Pendant - Sapphire (September)', imageSrc: IMG.c },
      { title: 'CZ Bezel Pendant - Sapphire (September)', imageSrc: IMG.d },
    ],
    isNew: true,
  }),
  item({
    id: 'aa-exh-stia',
    kbId: 'EXH',
    title: 'Stia',
    subtitle: '4 Lines Shown',
    description:
      'Contemporary jewelry exhibitor with matching September product stories and a digital showroom for post-market sourcing.',
    href: '/Discover',
    lob: 'exhibitor',
    perils: ['jewelry'],
    topics: ['atlanta', 'showroom'],
    searchBuckets: ['september', 'jewelry', 'exhibitor', 'showroom'],
    breadcrumb: ['Exhibitor Directory', 'Stia'],
    matchTerms: ['stia', 'september', 'jewelry', 'directory'],
    booth: 'B2 1-1204',
    linesShown: 4,
    matchingProducts: [
      { title: 'Winter Birthstone Stack', imageSrc: IMG.e },
      { title: 'September Layering Set', imageSrc: IMG.a },
      { title: 'Market Exclusive Charm', imageSrc: IMG.b },
    ],
  }),
  item({
    id: 'aa-exh-outdoor-living',
    kbId: 'EXH',
    title: 'Outdoor Living Collective',
    subtitle: '6 Lines Shown',
    description:
      'Outdoor apparel and patio lifestyle lines — pair the floor booth with the Outdoor Living Trends Talk before you register for market.',
    href: '/Discover',
    lob: 'exhibitor',
    perils: ['apparel', 'home'],
    topics: ['atlanta'],
    searchBuckets: ['outdoor', 'exhibitor', 'event', 'register'],
    breadcrumb: ['Exhibitor Directory', 'Outdoor Living Collective'],
    matchTerms: ['outdoor living', 'trends', 'patio', 'september market'],
    booth: 'A4 3-2210',
    linesShown: 6,
    matchingProducts: [
      { title: 'Resort Outerwear Look', imageSrc: IMG.c },
      { title: 'Patio Host Capsule', imageSrc: IMG.d },
    ],
  }),
  item({
    id: 'aa-exh-new-vibe',
    kbId: 'EXH',
    title: 'New Vibe Junior Fashion',
    subtitle: '3 Lines Shown',
    description:
      'Junior fashion lines showing during September market — attend the seminar, then add exhibitors to your Market Plan.',
    href: '/Discover',
    lob: 'exhibitor',
    perils: ['apparel'],
    topics: ['atlanta'],
    searchBuckets: ['fashion', 'exhibitor', 'event', 'september'],
    breadcrumb: ['Exhibitor Directory', 'New Vibe'],
    matchTerms: ['new vibe', 'junior', 'fashion', 'seminar'],
    booth: 'C1 8-0902',
    linesShown: 3,
    matchingProducts: [
      { title: 'Junior Market Drop', imageSrc: IMG.e },
      { title: 'Show Floor Exclusive', imageSrc: IMG.a },
    ],
  }),
  item({
    id: 'aa-evt-outdoor-talk',
    kbId: 'EVENT',
    title: 'Outdoor Living Trends Talk',
    subtitle: 'Trend Talk · Tue Sep 15, 2026 · 8:30–9:30 EST',
    description:
      'Start-of-day trend briefing in Oasis Meeting Space. Register for market first, then add this seminar to your plan.',
    href: '/Visit/Events/Outdoor-Living-Trends-Talk',
    lob: 'event',
    perils: ['seminar'],
    topics: ['atlanta'],
    searchBuckets: ['event', 'register', 'outdoor', 'september', 'seminar'],
    dateLabel: 'Tue Sep 15, 2026',
    breadcrumb: ['Visit', 'Events', 'Outdoor Living Trends Talk'],
    matchTerms: ['outdoor living', 'trends talk', 'seminar', 'oasis', 'register'],
    isNew: true,
  }),
  item({
    id: 'aa-evt-grand-opening',
    kbId: 'EVENT',
    title: 'Shoe and All Accessories Market Grand Opening',
    subtitle: 'Networking · Mon Sep 14, 2026',
    description:
      'Opening-night networking for shoe and accessories buyers. Physical attendance starts with market registration.',
    href: '/Visit/Events',
    lob: 'event',
    perils: ['networking'],
    topics: ['atlanta'],
    searchBuckets: ['event', 'register', 'accessories', 'september'],
    dateLabel: 'Mon Sep 14, 2026',
    breadcrumb: ['Visit', 'Events', 'Grand Opening'],
    matchTerms: ['grand opening', 'shoe', 'accessories', 'networking', 'register'],
  }),
  item({
    id: 'aa-evt-buyer-hub',
    kbId: 'EVENT',
    title: 'Buyer Grab-n-Go Hub',
    subtitle: 'Amenity · Tue Sep 15, 2026',
    description:
      'Buyer amenity hub between appointments. Use it after you register and build your Market Plan.',
    href: '/Visit/Events',
    lob: 'event',
    perils: ['amenity'],
    topics: ['atlanta'],
    searchBuckets: ['event', 'register', 'buyer', 'september'],
    dateLabel: 'Tue Sep 15, 2026',
    breadcrumb: ['Visit', 'Events', 'Buyer Grab-n-Go Hub'],
    matchTerms: ['buyer hub', 'grab-n-go', 'amenity'],
  }),
  item({
    id: 'aa-evt-best-brands',
    kbId: 'EVENT',
    title: 'Best Brands A Mid-day Mix',
    subtitle: 'Networking · Tue Sep 15, 2026',
    description: 'Mid-day mix for brand discovery. Registration required for floor and event access.',
    href: '/Visit/Events',
    lob: 'event',
    perils: ['networking'],
    topics: ['atlanta'],
    searchBuckets: ['event', 'register', 'september'],
    dateLabel: 'Tue Sep 15, 2026',
    breadcrumb: ['Visit', 'Events', 'Best Brands'],
    matchTerms: ['best brands', 'mid-day', 'networking'],
  }),
  item({
    id: 'aa-evt-new-vibe',
    kbId: 'EVENT',
    title: 'New Vibe Junior Fashion',
    subtitle: 'Seminar · Wed Sep 16, 2026',
    description:
      'Junior fashion seminar on the show calendar. Register, then add the session and nearby exhibitors to your plan.',
    href: '/Visit/Events',
    lob: 'event',
    perils: ['seminar'],
    topics: ['atlanta'],
    searchBuckets: ['event', 'register', 'fashion', 'seminar'],
    dateLabel: 'Wed Sep 16, 2026',
    breadcrumb: ['Visit', 'Events', 'New Vibe Junior Fashion'],
    matchTerms: ['new vibe', 'junior fashion', 'seminar'],
  }),
  item({
    id: 'aa-page-register',
    kbId: 'PAGE',
    title: 'Register for Market',
    subtitle: 'Visit · Registration',
    description:
      'Buyer registration for Atlanta Apparel. Physical market attendance starts here — first-time and returning buyers.',
    href: '/Visit/Registration',
    lob: 'page',
    perils: ['register'],
    topics: ['atlanta'],
    searchBuckets: ['register', 'buyer', 'market', 'september'],
    breadcrumb: ['Visit', 'Registration'],
    matchTerms: ['register', 'registration', 'sign in', 'buyer badge', 'market plan'],
    isNew: true,
  }),
  item({
    id: 'aa-page-first-time',
    kbId: 'PAGE',
    title: 'First-Time Buyers',
    subtitle: 'Registration path',
    description: 'First-time buyer registration steps, credentials, and what to expect on the floor.',
    href: '/Visit/Registration/First-Time-Buyers',
    lob: 'page',
    perils: ['register'],
    topics: ['atlanta'],
    searchBuckets: ['register', 'buyer'],
    breadcrumb: ['Visit', 'Registration', 'First-Time Buyers'],
    matchTerms: ['first-time', 'new buyer', 'register'],
  }),
  item({
    id: 'aa-page-returning',
    kbId: 'PAGE',
    title: 'Returning Buyers',
    subtitle: 'Registration path',
    description: 'Returning buyer sign-in and badge renewal — fastest path back onto the floor.',
    href: '/Visit/Registration/Returning-Buyers',
    lob: 'page',
    perils: ['register'],
    topics: ['atlanta'],
    searchBuckets: ['register', 'buyer'],
    breadcrumb: ['Visit', 'Registration', 'Returning Buyers'],
    matchTerms: ['returning', 'sign in', 'already registered'],
  }),
  item({
    id: 'aa-page-events',
    kbId: 'PAGE',
    title: 'Events & Seminars',
    subtitle: 'Visit · Events',
    description: 'Full September market calendar — seminars, trend talks, amenities, and networking.',
    href: '/Visit/Events',
    lob: 'page',
    perils: ['seminar'],
    topics: ['atlanta'],
    searchBuckets: ['event', 'seminar', 'september'],
    breadcrumb: ['Visit', 'Events'],
    matchTerms: ['events', 'seminars', 'calendar', 'all events'],
  }),
  item({
    id: 'aa-page-directory',
    kbId: 'PAGE',
    title: 'Exhibitor Directory',
    subtitle: 'Browse lines and booths',
    description:
      'Find exhibitors, booths, and lines — then add them to your Market Plan after you register.',
    href: '/Discover',
    lob: 'page',
    perils: ['apparel'],
    topics: ['atlanta', 'showroom'],
    searchBuckets: ['exhibitor', 'directory', 'showroom'],
    breadcrumb: ['Exhibitor Directory'],
    matchTerms: ['directory', 'exhibitors', 'booth', 'lines'],
  }),
  item({
    id: 'aa-art-september-guide',
    kbId: 'ARTICLE',
    title: 'How to work September market in one day',
    subtitle: 'Buyer guide',
    description:
      'Register, lock two seminars, then walk jewelry and outdoor-living booths — the same path Pulse recommends.',
    href: '/Visit/Events',
    lob: 'article',
    perils: ['seminar'],
    topics: ['atlanta'],
    searchBuckets: ['september', 'register', 'event', 'buyer'],
    breadcrumb: ['Discover', 'How to work September market'],
    matchTerms: ['september guide', 'buyer guide', 'one day market'],
  }),
  item({
    id: 'aa-art-year-round',
    kbId: 'ARTICLE',
    title: 'From show floor to year-round sourcing',
    subtitle: 'Omnichannel guide',
    description:
      'Use digital showrooms after market week so booth appointments become a 12-month sourcing relationship.',
    href: '/Discover',
    lob: 'article',
    perils: ['jewelry'],
    topics: ['showroom'],
    searchBuckets: ['showroom', 'exhibitor', 'buyer'],
    breadcrumb: ['Discover', 'Year-round sourcing'],
    matchTerms: ['year-round', 'omnichannel', 'digital showroom'],
  }),
];

export const atlantaApparelSearchPack: SearchSitePack = {
  siteName: 'atlanta-apparel',
  brandName: 'Atlanta Apparel',
  catalog,
  facetLabels: {
    lob: {
      exhibitor: 'Exhibitors & Products',
      event: 'Events & Seminars',
      page: 'Information',
      article: 'Articles',
    },
    peril: {
      jewelry: 'Jewelry',
      accessories: 'Accessories',
      apparel: 'Apparel',
      home: 'Home / outdoor',
      seminar: 'Seminars & talks',
      networking: 'Networking',
      amenity: 'Amenities',
      register: 'Registration',
    },
    topic: {
      atlanta: 'Atlanta market',
      showroom: 'Digital showroom',
    },
  },
  bucketSynonyms: {
    september: ['september', 'sept', 'fall market', 'september market'],
    jewelry: ['jewelry', 'jewel', 'sapphire', 'pendant', 'cz'],
    exhibitor: ['exhibitor', 'directory', 'booth', 'line', 'lines'],
    showroom: ['showroom', 'digital showroom', 'year-round'],
    outdoor: ['outdoor', 'outdoor living', 'patio', 'oasis'],
    event: ['event', 'events', 'seminar', 'seminars', 'talk', 'calendar'],
    register: ['register', 'registration', 'badge', 'sign in', 'signin'],
    buyer: ['buyer', 'buyers', 'market plan', 'plan'],
    market: ['market', 'markets', 'atlanta apparel'],
    seminar: ['seminar', 'trend talk', 'keynote'],
    fashion: ['fashion', 'junior', 'apparel'],
    accessories: ['accessories', 'shoe', 'jewelry'],
    directory: ['directory', 'exhibitors'],
  },
  popularSearches: [
    'september',
    'Register for September market',
    'Outdoor Living Trends Talk',
    'Exhibitor directory jewelry',
    'First-time buyer registration',
  ],
  insightRules: [
    {
      id: 'register-market',
      matchAny: [
        ['register'],
        ['registration'],
        ['sign', 'in'],
        ['buyer', 'badge'],
        ['market', 'plan'],
        ['first-time'],
        ['returning', 'buyer'],
      ],
      insight: {
        id: 'ai-aa-register',
        headline: 'Register first — then build the Market Plan',
        answer:
          'Atlanta Apparel’s digital path is built to get buyers onto the physical floor. Open Registration, choose First-Time or Returning Buyers, then add seminars and exhibitors to your plan so show-week appointments continue in the year-round showroom.',
        bullets: [
          'Registration is the conversion step for physical attendance.',
          'Returning buyers should Sign In to resume a Market Plan.',
          'Pair a seminar (Outdoor Living Trends Talk) with nearby exhibitors.',
        ],
        citations: [
          {
            title: 'Register for Market',
            href: '/Visit/Registration',
            kbId: 'PAGE',
            excerpt: 'Buyer registration for Atlanta Apparel.',
          },
          {
            title: 'Events & Seminars',
            href: '/Visit/Events',
            kbId: 'PAGE',
            excerpt: 'September market calendar.',
          },
        ],
        learnMoreHref: '/Visit/Registration',
        learnMoreLabel: 'Register for market',
        stateCallout: 'Funnel: search → register → event + exhibitor plan.',
      },
    },
    {
      id: 'september-events',
      matchAny: [
        ['september'],
        ['outdoor', 'living'],
        ['trends', 'talk'],
        ['seminar'],
        ['event'],
        ['calendar'],
      ],
      insight: {
        id: 'ai-aa-events',
        headline: 'September market: register, then lock the talk',
        answer:
          'A September search should surface the show calendar and the exhibitors those sessions feed. Register for market access, add Outdoor Living Trends Talk, then walk the matching booths and keep those lines in the digital showroom after you leave Atlanta.',
        bullets: [
          'Open Events for the dated seminar list.',
          'Outdoor Living Trends Talk is the Tuesday 8:30 briefing.',
          'Use Register if you are not already credentialed.',
        ],
        citations: [
          {
            title: 'Outdoor Living Trends Talk',
            href: '/Visit/Events/Outdoor-Living-Trends-Talk',
            kbId: 'EVENT',
            excerpt: 'Tue Sep 15, 2026 · Oasis Meeting Space.',
          },
          {
            title: 'Register for Market',
            href: '/Visit/Registration',
            kbId: 'PAGE',
            excerpt: 'Required for physical attendance.',
          },
        ],
        learnMoreHref: '/Visit/Events',
        learnMoreLabel: 'Browse events & seminars',
        stateCallout: 'Demo query: september → events tab + register CTA.',
      },
    },
    {
      id: 'directory-showroom',
      matchAny: [['exhibitor'], ['directory'], ['jewelry'], ['booth'], ['showroom'], ['anna', 'ober']],
      insight: {
        id: 'ai-aa-directory',
        headline: 'Find the booth, then add it to the plan',
        answer:
          'Directory results are the sourcing half of the funnel. Add exhibitors to your Market Plan (registration / sign-in) so floor appointments become year-round digital reorders.',
        bullets: [
          'Anna Ober & Co. is the September jewelry example from the live directory.',
          'Add To Plan routes buyers who are not signed in into Registration.',
        ],
        citations: [
          {
            title: 'Exhibitor Directory',
            href: '/Discover',
            kbId: 'PAGE',
            excerpt: 'Browse lines and booths.',
          },
          {
            title: 'Register for Market',
            href: '/Visit/Registration',
            kbId: 'PAGE',
            excerpt: 'Create the Market Plan after you register.',
          },
        ],
        learnMoreHref: '/Visit/Registration',
        learnMoreLabel: 'Sign in to create your Market Plan',
      },
    },
  ],
  copy: {
    kicker: 'Atlanta Apparel search',
    headingEmpty: 'Find exhibitors, events & register for market',
    intro:
      'Search the way buyers shop Atlanta Apparel: find a line or a September seminar, then register so you can attend in person and keep sourcing year-round.',
    placeholder: 'Search exhibitors, events, September market…',
    emptyHint: 'Try “september,” “Outdoor Living Trends Talk,” or “register for market.”',
    resultsHint: ' — try a starter search or a booth / event name',
    aiHeading: 'Get to market',
    citationsHeading: 'Next step',
    facetLob: 'Result type',
    facetPeril: 'Category',
    facetTopic: 'Market',
    tips: [
      {
        title: 'Register is the conversion',
        body: 'Directory and events are the discovery layer. Registration is how buyers get on the floor.',
      },
      {
        title: 'Pair a talk with a booth',
        body: 'Search “september” or “outdoor living” to land the seminar plus nearby exhibitors.',
      },
      {
        title: 'Keep sourcing after market',
        body: 'Add To Plan and the digital showroom turn a three-day visit into year-round reorders.',
      },
    ],
  },
  ctaByLob: {
    exhibitor: 'View exhibitor',
    event: 'View event',
    page: 'Open page',
    article: 'Read article',
  },
  defaultCta: 'Open page',
  iconByLob: {
    exhibitor: Store,
    event: CalendarDays,
    page: FileText,
    article: Newspaper,
  },
  featuredLob: 'event',
  enableDemoPersona: false,
  registerHref: '/Visit/Registration',
  signInHref: '/Visit/Registration/Returning-Buyers',
};
