---
ID: "053c6d0c-3611-4811-86d1-b35ab1875d0f"
Parent: "e7dda8f5-e1cc-4568-87cb-0362cae6c449"
Template: "e7dda8f5-e1cc-4568-87cb-0362cae6c449"
Path: /sitecore/templates/Project/Cooley/Folders/NewsListing Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{DE22037D-099B-40FD-895E-AF11C08FD8EE}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e37c60c5-ecb0-4a00-aa06-1a90ad50e379"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260817T000132Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "472a530a-2261-4b14-bb5c-3dc1e7a71e49"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260817T000141Z
