---
ID: "166992ba-7649-46d0-b9f3-2cd69331ffce"
Parent: "49cc45fe-dff7-4bdd-8fe6-84929f3bac18"
Template: "49cc45fe-dff7-4bdd-8fe6-84929f3bac18"
Path: "/sitecore/templates/Project/granite-parnters/Partial Design Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {49CC45FE-DFF7-4BDD-8FE6-84929F3BAC18}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "172681bb-6ea8-40e5-b19c-aa3abd974d83"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260617T114526Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "03c74712-36a2-456a-ab8a-30e21d7d6b68"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260617T114532Z
