import { FileText, Layers, Wrench } from 'lucide-react';

import type { SearchResultItem, SearchSitePack } from './types';

const catalog: SearchResultItem[] = [
  {
    id: 'at-maxim-hp',
    kbId: 'PDP',
    title: 'Maxim HP Hinge',
    description: 'High-performance hinge for casement and awning windows.',
    href: '/Products/Windows/Casement Awning/Maxim HP Hinge',
    lob: 'product',
    perils: ['windowHardware'],
    topics: ['windows'],
    searchBuckets: ['hinge', 'casement', 'window'],
    breadcrumb: ['Products', 'Windows', 'Casement Awning'],
    matchTerms: ['maxim hp', 'casement hinge', 'awning'],
    isNew: true,
  },
  {
    id: 'at-p3000',
    kbId: 'PDP',
    title: 'P3000',
    description: 'Multipoint lock system for windows and patio doors.',
    href: '/Products/Windows/Locks/P3000',
    lob: 'product',
    perils: ['locks'],
    topics: ['windows', 'doors'],
    searchBuckets: ['lock', 'multipoint', 'window'],
    breadcrumb: ['Products', 'Windows', 'Locks'],
    matchTerms: ['p3000', 'multipoint lock'],
  },
  {
    id: 'at-safegard',
    kbId: 'PDP',
    title: 'SafeGard 2',
    description: 'Window opening control device for safer sash travel.',
    href: '/Products/Windows/Safety/SafeGard 2',
    lob: 'product',
    perils: ['windowHardware'],
    topics: ['windows'],
    searchBuckets: ['window', 'safety'],
    breadcrumb: ['Products', 'Windows', 'Safety'],
    matchTerms: ['safegard', 'restrictor', 'window safety'],
  },
  {
    id: 'at-pile',
    kbId: 'HUB',
    title: 'Pile Weatherseals',
    description: 'Pile weatherseals and door sweeps for fenestration sealing.',
    href: '/Products/Weatherseals',
    lob: 'product',
    perils: ['weatherseals'],
    topics: ['windows', 'doors'],
    searchBuckets: ['weatherseal', 'pile'],
    breadcrumb: ['Products', 'Weatherseals'],
    matchTerms: ['pile', 'weatherseal', 'door sweep'],
  },
  {
    id: 'at-warranty',
    kbId: 'PAGE',
    title: 'Warranty & technical notes',
    description: 'Warranty information and technical notes for AmesburyTruth hardware.',
    href: '/Support',
    lob: 'support',
    perils: ['windowHardware'],
    topics: ['windows'],
    searchBuckets: ['support'],
    breadcrumb: ['Support'],
    matchTerms: ['warranty', 'technical notes'],
  },
];

export const amesburytruthSearchPack: SearchSitePack = {
  siteName: 'amesburytruth',
  brandName: 'AmesburyTruth',
  catalog,
  facetLabels: {
    lob: { product: 'Products', support: 'Support', page: 'Pages' },
    peril: {
      windowHardware: 'Window hardware',
      locks: 'Locks',
      weatherseals: 'Weatherseals',
    },
    topic: { windows: 'Windows', doors: 'Doors' },
  },
  bucketSynonyms: {
    hinge: ['hinge', 'maxim'],
    casement: ['casement', 'awning'],
    window: ['window', 'sash'],
    lock: ['lock', 'p3000'],
    multipoint: ['multipoint', 'multi-point'],
    safety: ['safegard', 'restrictor', 'safety'],
    weatherseal: ['weatherseal', 'pile', 'sweep'],
    pile: ['pile', 'fin-seal'],
    support: ['warranty', 'technical', 'support'],
  },
  popularSearches: [
    'Casement window hinges',
    'P3000 multipoint locks',
    'Pile weatherseals',
    'SafeGard window safety',
  ],
  insightRules: [
    {
      id: 'at-windows',
      matchAny: [['casement'], ['hinge'], ['window', 'hardware']],
      insight: {
        id: 'ai-at-windows',
        headline: 'Window hardware first, then the seal',
        answer:
          'AmesburyTruth search is operator-and-hinge led. Pair Maxim HP with weatherseals when the demo needs a complete window opening.',
        bullets: ['Start with Maxim HP for casement/awning, then pile weatherseals for the frame.'],
        citations: [
          {
            title: 'Maxim HP Hinge',
            href: '/Products/Windows/Casement Awning/Maxim HP Hinge',
            kbId: 'PDP',
          },
        ],
        learnMoreHref: '/Products/Windows',
        learnMoreLabel: 'Browse window hardware',
      },
    },
  ],
  copy: {
    kicker: 'AmesburyTruth search',
    headingEmpty: 'Find window, door & weatherseal hardware',
    intro:
      'Search casement operators, locks, and pile weatherseals the way fenestration OEMs specify AmesburyTruth.',
    placeholder: 'Search Maxim HP, P3000, pile weatherseals…',
    emptyHint: 'Try “casement hinge,” “P3000,” or “pile weatherseal.”',
    resultsHint: ' — try a starter search',
    aiHeading: 'Specification guidance',
    citationsHeading: 'Recommended products',
    facetLob: 'Content type',
    facetPeril: 'Product family',
    facetTopic: 'Application',
    tips: [
      { title: 'Hardware then seal', body: 'Search hinges/operators first, then weatherseals for the same opening.' },
      { title: 'Use product names', body: 'Maxim HP, P3000, and SafeGard map directly to demo PDPs.' },
      { title: 'Support is separate', body: 'Warranty and technical notes live under Support, not product hubs.' },
    ],
  },
  ctaByLob: { product: 'View product', support: 'Open support', page: 'Open page' },
  defaultCta: 'Open page',
  iconByLob: { product: Layers, support: Wrench, page: FileText },
  featuredLob: 'product',
  enableDemoPersona: false,
};
