import { FileText, Layers, Wrench } from 'lucide-react';

import type { SearchResultItem, SearchSitePack } from './types';

const catalog: SearchResultItem[] = [
  {
    id: 'era-flag-hinge',
    kbId: 'PDP',
    title: 'Classic Flag Hinge for PVCu Doors',
    description: 'Fully adjustable Fab&Fix Classic Flag Hinge for PVCu entrance doors.',
    href: '/Door Components/Entrance Doors/Door Hinges/Classic Flag Hinge for PVCu Doors',
    lob: 'product',
    perils: ['hinges'],
    topics: ['doors'],
    searchBuckets: ['hinge', 'door', 'pvcu'],
    breadcrumb: ['Door Components', 'Entrance Doors', 'Door Hinges'],
    matchTerms: ['flag hinge', 'fab&fix', 'entrance door'],
    isNew: true,
  },
  {
    id: 'era-letterplate',
    kbId: 'PDP',
    title: 'Architectural Shield TS 008 External Letterplate',
    description: 'TS 008 letterplate solution to help prevent fishing attacks on PAS 24 doors.',
    href: '/Door Components/Entrance Doors/Letterplates/Architectural Shield TS 008 External Letterplate',
    lob: 'product',
    perils: ['letterplates'],
    topics: ['doors'],
    searchBuckets: ['letterplate', 'door', 'security'],
    breadcrumb: ['Door Components', 'Entrance Doors', 'Letterplates'],
    matchTerms: ['letterplate', 'ts 008', 'pas 24'],
  },
  {
    id: 'era-balmoral',
    kbId: 'PDP',
    title: 'Balmoral Sprung Inline Lever Lever Door Handle',
    description: 'Classic Fab&Fix lever-lever handle for Euro cylinder multi-point locks.',
    href: '/Door Components/Entrance Doors/Door Handles/Balmoral Sprung Inline Lever Lever Door Handle',
    lob: 'product',
    perils: ['handles'],
    topics: ['doors'],
    searchBuckets: ['handle', 'door', 'multipoint'],
    breadcrumb: ['Door Components', 'Entrance Doors', 'Door Handles'],
    matchTerms: ['balmoral', 'door handle', 'euro cylinder'],
  },
  {
    id: 'era-connoisseur',
    kbId: 'PDP',
    title: 'Connoisseur Inline Locking Window Handle',
    description: 'Key-locking espagnolette window handle for casement windows.',
    href: '/Window Components/Casement Windows/Window Handles/Connoisseur Inline Locking Window Handle',
    lob: 'product',
    perils: ['handles'],
    topics: ['windows'],
    searchBuckets: ['handle', 'window', 'casement'],
    breadcrumb: ['Window Components', 'Casement Windows', 'Window Handles'],
    matchTerms: ['connoisseur', 'window handle', 'espagnolette'],
  },
  {
    id: 'era-protect',
    kbId: 'PDP',
    title: 'ERA Protect Smart Handle',
    description: 'Connected smart handle in the ERA Protect home security ecosystem.',
    href: '/Home Security/ERA Protect Ecosystem/ERA Protect Smart Handle',
    lob: 'product',
    perils: ['smart'],
    topics: ['security'],
    searchBuckets: ['smart', 'security', 'handle'],
    breadcrumb: ['Home Security', 'ERA Protect Ecosystem'],
    matchTerms: ['era protect', 'smart handle', 'app'],
  },
  {
    id: 'era-support',
    kbId: 'PAGE',
    title: 'Customer Service',
    description: 'Technical downloads, support, and how to get help with ERA products.',
    href: '/Support',
    lob: 'support',
    perils: ['handles'],
    topics: ['security'],
    searchBuckets: ['support'],
    breadcrumb: ['Support'],
    matchTerms: ['technical', 'download', 'customer service'],
  },
];

export const eraSearchPack: SearchSitePack = {
  siteName: 'era',
  brandName: 'ERA',
  catalog,
  facetLabels: {
    lob: { product: 'Products', support: 'Support', page: 'Pages' },
    peril: {
      hinges: 'Hinges',
      handles: 'Handles',
      letterplates: 'Letterplates',
      smart: 'Smart security',
    },
    topic: { doors: 'Doors', windows: 'Windows', security: 'Home security' },
  },
  bucketSynonyms: {
    hinge: ['hinge', 'flag hinge'],
    door: ['door', 'entrance'],
    pvcu: ['pvcu', 'pvc', 'upvc'],
    letterplate: ['letterplate', 'letter plate', 'ts 008'],
    security: ['security', 'pas 24', 'sbd'],
    handle: ['handle', 'lever'],
    multipoint: ['multi-point', 'multipoint', 'euro'],
    window: ['window', 'casement'],
    casement: ['casement', 'espagnolette'],
    smart: ['smart', 'protect', 'connected'],
    support: ['support', 'download', 'technical'],
  },
  popularSearches: [
    'PVCu door hinges',
    'Casement window handles',
    'TS 008 letterplates',
    'ERA Protect smart handle',
  ],
  insightRules: [
    {
      id: 'era-doors',
      matchAny: [['door'], ['hinge'], ['letterplate'], ['handle']],
      insight: {
        id: 'ai-era-doors',
        headline: 'Entrance-door hardware that works as a set',
        answer:
          'ERA search is hardware-led: hinges, handles, letterplates, and multipoint locks are meant to be specified together for PAS 24 doorsets.',
        bullets: [
          'Start with Classic Flag Hinge or Balmoral handle, then add the matching letterplate.',
        ],
        citations: [
          {
            title: 'Classic Flag Hinge for PVCu Doors',
            href: '/Door Components/Entrance Doors/Door Hinges/Classic Flag Hinge for PVCu Doors',
            kbId: 'PDP',
          },
        ],
        learnMoreHref: '/Door Components',
        learnMoreLabel: 'Browse door components',
      },
    },
  ],
  copy: {
    kicker: 'ERA search',
    headingEmpty: 'Find door, window & security hardware',
    intro:
      'Search ERA and Fab&Fix hardware the way installers specify it: hinges, handles, letterplates, and connected security.',
    placeholder: 'Search hinges, window handles, ERA Protect…',
    emptyHint: 'Try “flag hinge,” “casement handle,” or “ERA Protect.”',
    resultsHint: ' — try a starter search',
    aiHeading: 'Specification guidance',
    citationsHeading: 'Recommended products',
    facetLob: 'Content type',
    facetPeril: 'Hardware type',
    facetTopic: 'Application',
    tips: [
      { title: 'Search the hardware', body: 'Use product families—hinges, handles, letterplates—not generic “doors.”' },
      { title: 'Match the system', body: 'PAS 24 doorsets usually need hinge + handle + letterplate together.' },
      { title: 'Smart security', body: 'ERA Protect is the connected ecosystem, not a standalone lock page.' },
    ],
  },
  ctaByLob: { product: 'View product', support: 'Open support', page: 'Open page' },
  defaultCta: 'Open page',
  iconByLob: { product: Layers, support: Wrench, page: FileText },
  featuredLob: 'product',
  enableDemoPersona: false,
};
