import { Building2, CalendarCheck, Ear, HeartPulse, Stethoscope } from 'lucide-react';

import {
  LCMC_DEMO_ENT_PHYSICIAN_NAME,
  LCMC_DEMO_MOREAU_SICK_HREF,
  LCMC_ENT_SPECIALTY,
  LCMC_WJMC_LOCATION_NAME,
} from '@/lib/lcmc-appointment-pack';

import type { AiCitation, SearchResultItem, SearchSitePack } from './types';

function item(partial: SearchResultItem): SearchResultItem {
  return partial;
}

const LCMC_ENT_PHYSICIAN_CITATIONS: AiCitation[] = [
  {
    title: LCMC_DEMO_ENT_PHYSICIAN_NAME,
    href: '/Find-a-Provider/Gabrielle-Moreau-MD',
    kbId: 'MD',
    excerpt: 'ENT at West Jefferson Medical Center — book a visit.',
  },
  {
    title: 'Dominic Lirette, MD',
    href: '/Find-a-Provider/Dominic-Lirette-MD',
    kbId: 'MD',
    excerpt: 'ENT at West Jefferson Medical Center.',
  },
];

/**
 * LCMC Health SearchResults pack — same story as Pulse: physicians, WJMC,
 * ENT / sinus, book an appointment. Isolated from Quanex / Pillsbury / Amkor.
 */
const catalog: SearchResultItem[] = [
  item({
    id: 'lcmc-wjmc',
    kbId: 'LOC',
    title: LCMC_WJMC_LOCATION_NAME,
    subtitle: 'Hospital · Marrero',
    description:
      'West Jefferson Medical Center (often searched as West Jefferson Medical Clinic) is an LCMC Health hospital in Marrero — the demo home for ENT visits with Gabrielle Moreau, MD.',
    href: '/Our-Locations/West-Jefferson-Medical-Center',
    lob: 'locations',
    perils: ['wjmc', 'ent'],
    topics: ['hospital', 'marrero'],
    searchBuckets: ['locations', 'wjmc', 'ent'],
    breadcrumb: ['Our Locations', LCMC_WJMC_LOCATION_NAME],
    matchTerms: [
      'west jefferson',
      'west jefferson medical clinic',
      'wjmc',
      'marrero',
      'hospital',
      'location',
    ],
    isNew: true,
  }),
  item({
    id: 'lcmc-wjmc-hub',
    kbId: 'LOC',
    title: 'West Jefferson Medical Center site',
    subtitle: 'Hospital microsite',
    description:
      'Services, patients and visitors, and locations for the West Jefferson campus — including Ears, Nose and Throat Care.',
    href: '/West-Jefferson-Medical-Center',
    lob: 'locations',
    perils: ['wjmc'],
    topics: ['hospital', 'marrero'],
    searchBuckets: ['locations', 'wjmc', 'ent'],
    breadcrumb: ['West Jefferson Medical Center'],
    matchTerms: ['west jefferson', 'wjmc', 'clinic', 'campus'],
  }),
  item({
    id: 'lcmc-ejgh',
    kbId: 'LOC',
    title: 'East Jefferson General Hospital',
    subtitle: 'Hospital · Metairie',
    description: 'East Jefferson General Hospital is an LCMC Health hospital on the East Bank.',
    href: '/Our-Locations/East-Jefferson-General-Hospital',
    lob: 'locations',
    perils: ['ejgh'],
    topics: ['hospital', 'metairie'],
    searchBuckets: ['locations'],
    breadcrumb: ['Our Locations', 'East Jefferson General Hospital'],
    matchTerms: ['east jefferson', 'ejgh', 'metairie'],
  }),
  item({
    id: 'lcmc-umc',
    kbId: 'LOC',
    title: 'University Medical Center New Orleans',
    subtitle: 'Hospital · New Orleans',
    description: 'University Medical Center New Orleans is the academic medical center in the LCMC Health system.',
    href: '/Our-Locations/University-Medical-Center-New-Orleans',
    lob: 'locations',
    perils: ['umc'],
    topics: ['hospital'],
    searchBuckets: ['locations'],
    breadcrumb: ['Our Locations', 'University Medical Center New Orleans'],
    matchTerms: ['umc', 'university medical', 'new orleans'],
  }),
  item({
    id: 'lcmc-touro',
    kbId: 'LOC',
    title: 'Touro',
    subtitle: 'Hospital · Uptown',
    description: 'Touro is an LCMC Health hospital serving Uptown New Orleans and surrounding neighborhoods.',
    href: '/Our-Locations/Touro',
    lob: 'locations',
    perils: ['touro'],
    topics: ['hospital'],
    searchBuckets: ['locations'],
    breadcrumb: ['Our Locations', 'Touro'],
    matchTerms: ['touro', 'uptown'],
  }),
  item({
    id: 'lcmc-locations',
    kbId: 'HUB',
    title: 'Our Locations',
    subtitle: 'Hospitals and clinics',
    description: 'Browse LCMC Health hospitals and clinics across Greater New Orleans.',
    href: '/Our-Locations',
    lob: 'locations',
    perils: ['directory'],
    topics: ['hospital'],
    searchBuckets: ['locations'],
    breadcrumb: ['Our Locations'],
    matchTerms: ['locations', 'hospitals', 'clinics', 'find a location'],
  }),
  item({
    id: 'lcmc-moreau',
    kbId: 'MD',
    title: LCMC_DEMO_ENT_PHYSICIAN_NAME,
    subtitle: `${LCMC_ENT_SPECIALTY} · ${LCMC_WJMC_LOCATION_NAME}`,
    description:
      'Board-certified ENT / otolaryngologist at West Jefferson Medical Center. Demo provider for sinus, ear, and throat visits — book from Patient Appointments.',
    href: '/Find-a-Provider/Gabrielle-Moreau-MD',
    lob: 'providers',
    perils: ['ent'],
    topics: ['sinus', 'hearing'],
    searchBuckets: ['providers', 'ent', 'wjmc'],
    breadcrumb: ['Find a Provider', LCMC_DEMO_ENT_PHYSICIAN_NAME],
    matchTerms: [
      'gabrielle moreau',
      'ent',
      'otolaryngology',
      'sinus',
      'ear',
      'throat',
      'west jefferson',
      'doctor',
      'physician',
      'specialist',
    ],
    isNew: true,
  }),
  item({
    id: 'lcmc-lirette',
    kbId: 'MD',
    title: 'Dominic Lirette, MD',
    subtitle: `${LCMC_ENT_SPECIALTY} · ${LCMC_WJMC_LOCATION_NAME}`,
    description:
      'ENT physician at West Jefferson Medical Center — second ENT in the Find a Provider / appointment demo alongside Gabrielle Moreau.',
    href: '/Find-a-Provider/Dominic-Lirette-MD',
    lob: 'providers',
    perils: ['ent'],
    topics: ['sinus', 'hearing'],
    searchBuckets: ['providers', 'ent', 'wjmc'],
    breadcrumb: ['Find a Provider', 'Dominic Lirette, MD'],
    matchTerms: ['dominic lirette', 'ent', 'otolaryngology', 'west jefferson', 'doctor'],
  }),
  item({
    id: 'lcmc-landry',
    kbId: 'MD',
    title: 'Camille Landry, MD, FACC',
    subtitle: `Cardiology · East Jefferson General Hospital`,
    description: 'Cardiologist at East Jefferson General Hospital — contrast to the ENT West Jefferson story.',
    href: '/Find-a-Provider/Camille-Landry-MD',
    lob: 'providers',
    perils: ['cardiology'],
    topics: ['heart'],
    searchBuckets: ['providers', 'cardiology'],
    breadcrumb: ['Find a Provider', 'Camille Landry, MD, FACC'],
    matchTerms: ['camille landry', 'cardiology', 'heart', 'east jefferson'],
  }),
  item({
    id: 'lcmc-find-provider',
    kbId: 'HUB',
    title: 'Find a Provider',
    subtitle: 'Physician directory',
    description:
      'Search published LCMC Health physicians by specialty and location — the same catalog Pulse and Patient Appointments use.',
    href: '/Find-a-Provider',
    lob: 'providers',
    perils: ['directory'],
    topics: ['directory'],
    searchBuckets: ['providers'],
    breadcrumb: ['Find a Provider'],
    matchTerms: ['find a provider', 'doctor', 'physician', 'directory', 'specialist'],
  }),
  item({
    id: 'lcmc-ent-system',
    kbId: 'SVC',
    title: 'Ears, Nose and Throat Care',
    subtitle: 'ENT / otolaryngology',
    description:
      'ENT services across LCMC Health — sinus, hearing, tonsils, and throat care. Pair with West Jefferson specialists for the demo.',
    href: '/Our-Services/Ears-Nose-and-Throat-Care',
    lob: 'ent',
    perils: ['ent'],
    topics: ['sinus', 'hearing'],
    searchBuckets: ['ent', 'services'],
    breadcrumb: ['Our Services', 'Ears, Nose and Throat Care'],
    matchTerms: [
      'ent',
      'ear nose throat',
      'otolaryngology',
      'sinus',
      'hearing',
      'tonsil',
      'sore throat',
    ],
    isNew: true,
  }),
  item({
    id: 'lcmc-wjmc-ent',
    kbId: 'SVC',
    title: 'ENT care at West Jefferson',
    subtitle: 'WJMC Ears, Nose and Throat',
    description:
      'Ears, Nose and Throat Care on the West Jefferson Medical Center campus — sinus, ear, and throat programs in Marrero.',
    href: '/West-Jefferson-Medical-Center/Our-Services/Ears-Nose-and-Throat-Care',
    lob: 'ent',
    perils: ['ent', 'wjmc'],
    topics: ['sinus', 'hearing'],
    searchBuckets: ['ent', 'wjmc', 'services'],
    breadcrumb: ['West Jefferson Medical Center', 'Our Services', 'Ears Nose and Throat Care'],
    matchTerms: ['ent', 'west jefferson', 'sinus', 'ear', 'nose', 'throat', 'wjmc'],
  }),
  item({
    id: 'lcmc-wjmc-ear',
    kbId: 'SVC',
    title: 'Ear care',
    subtitle: 'Hearing, balance, ear surgery',
    description: 'Ear care at West Jefferson — hearing, balance problems, and surgical ear treatments.',
    href: '/West-Jefferson-Medical-Center/Our-Services/Ears-Nose-and-Throat-Care/Ear',
    lob: 'ent',
    perils: ['ent', 'ear'],
    topics: ['hearing'],
    searchBuckets: ['ent', 'wjmc', 'services'],
    breadcrumb: ['West Jefferson Medical Center', 'ENT', 'Ear'],
    matchTerms: ['ear', 'hearing', 'tinnitus', 'balance', 'west jefferson'],
  }),
  item({
    id: 'lcmc-wjmc-nose',
    kbId: 'SVC',
    title: 'Nasal and sinus care',
    subtitle: 'Allergies and sinus',
    description:
      'Nasal and sinus care at West Jefferson — allergies, sinus infections, and breathing trouble that keep you out of the parade.',
    href: '/West-Jefferson-Medical-Center/Our-Services/Ears-Nose-and-Throat-Care/Nose',
    lob: 'ent',
    perils: ['ent', 'sinus'],
    topics: ['sinus'],
    searchBuckets: ['ent', 'wjmc', 'services'],
    breadcrumb: ['West Jefferson Medical Center', 'ENT', 'Nose'],
    matchTerms: ['nose', 'sinus', 'allergy', 'nasal', 'west jefferson'],
  }),
  item({
    id: 'lcmc-wjmc-throat',
    kbId: 'SVC',
    title: 'Throat, neck, and face care',
    subtitle: 'Throat and neck',
    description: 'Throat, neck, and face care at West Jefferson — from sore throats to neck concerns.',
    href: '/West-Jefferson-Medical-Center/Our-Services/Ears-Nose-and-Throat-Care/Throat-Neck-and-Face-Care',
    lob: 'ent',
    perils: ['ent', 'throat'],
    topics: ['throat'],
    searchBuckets: ['ent', 'wjmc', 'services'],
    breadcrumb: ['West Jefferson Medical Center', 'ENT', 'Throat Neck and Face Care'],
    matchTerms: ['throat', 'neck', 'tonsils', 'sore throat', 'west jefferson'],
  }),
  item({
    id: 'lcmc-heart',
    kbId: 'SVC',
    title: 'Heart and Vascular Care',
    subtitle: 'Cardiology',
    description: 'Heart and vascular care across LCMC Health hospitals.',
    href: '/Our-Services/Heart-and-Vascular-Care',
    lob: 'services',
    perils: ['cardiology'],
    topics: ['heart'],
    searchBuckets: ['services', 'cardiology'],
    breadcrumb: ['Our Services', 'Heart and Vascular Care'],
    matchTerms: ['heart', 'cardiology', 'vascular', 'cardiac'],
  }),
  item({
    id: 'lcmc-services',
    kbId: 'HUB',
    title: 'Our Services',
    subtitle: 'Clinical programs',
    description: 'Clinical services across LCMC Health — ENT, heart, and more.',
    href: '/Our-Services',
    lob: 'services',
    perils: ['directory'],
    topics: ['directory'],
    searchBuckets: ['services'],
    breadcrumb: ['Our Services'],
    matchTerms: ['services', 'programs', 'specialty'],
  }),
  item({
    id: 'lcmc-appointments',
    kbId: 'PAGE',
    title: 'Patient Appointments',
    subtitle: 'Book a visit',
    description:
      'Schedule a visit. Deep links can skip visit type and pre-select ENT, West Jefferson, and Gabrielle Moreau.',
    href: LCMC_DEMO_MOREAU_SICK_HREF,
    lob: 'appointments',
    perils: ['ent', 'wjmc'],
    topics: ['booking'],
    searchBuckets: ['appointments', 'ent', 'wjmc'],
    breadcrumb: ['For Patients', 'Patient Appointments'],
    matchTerms: ['appointment', 'book', 'schedule', 'sick visit', 'ent', 'west jefferson'],
    isNew: true,
  }),
];

export const lcmcSearchPack: SearchSitePack = {
  siteName: 'lcmc',
  brandName: 'LCMC Health',
  catalog,
  facetLabels: {
    lob: {
      providers: 'Providers',
      locations: 'Locations',
      ent: 'ENT care',
      services: 'Services',
      appointments: 'Appointments',
    },
    peril: {
      ent: 'ENT',
      wjmc: 'West Jefferson',
      cardiology: 'Cardiology',
      sinus: 'Sinus',
      ear: 'Ear',
      throat: 'Throat',
      directory: 'Directory',
      ejgh: 'East Jefferson',
      umc: 'UMC',
      touro: 'Touro',
    },
    topic: {
      hospital: 'Hospital',
      marrero: 'Marrero',
      metairie: 'Metairie',
      sinus: 'Sinus',
      hearing: 'Hearing',
      heart: 'Heart',
      directory: 'Directory',
      throat: 'Throat',
      booking: 'Booking',
    },
  },
  bucketSynonyms: {
    ent: [
      'ent',
      'ear',
      'nose',
      'throat',
      'sinus',
      'hearing',
      'tonsil',
      'otolaryngology',
      'otolaryngologist',
      'oido',
      'garganta',
    ],
    wjmc: [
      'west jefferson',
      'wjmc',
      'jefferson medical clinic',
      'jefferson medical center',
      'marrero',
    ],
    providers: ['doctor', 'physician', 'provider', 'specialist', 'medico'],
    locations: ['location', 'hospital', 'clinic', 'campus'],
    appointments: ['appointment', 'book', 'schedule', 'cita'],
    services: ['service', 'care', 'program'],
    cardiology: ['heart', 'cardiac', 'cardiology'],
  },
  popularSearches: [
    'ENT West Jefferson',
    'sinus specialist',
    'Gabrielle Moreau',
    'West Jefferson Medical Clinic',
    'book an appointment',
  ],
  insightRules: [
    {
      id: 'ent-sinus-wjmc',
      matchAny: [
        ['sinus', 'west'],
        ['sinus', 'jefferson'],
        ['someone', 'sinus'],
        ['ent'],
        ['sinus'],
        ['ear', 'nose'],
        ['otolaryng'],
        ['sore', 'throat'],
        ['hearing'],
        ['tonsil'],
      ],
      insight: {
        id: 'ai-lcmc-ent',
        headline: 'See ENT physicians at West Jefferson',
        answer:
          'For sinus, ear, or throat care near West Jefferson, start with Gabrielle Moreau, MD or Dominic Lirette, MD. Both practice ENT at West Jefferson Medical Center — open a profile, then book from Patient Appointments.',
        bullets: [
          'Gabrielle Moreau, MD — demo ENT at WJMC.',
          'Dominic Lirette, MD — second ENT at WJMC.',
          'West Jefferson Medical Center (clinic nickname maps to the hospital).',
        ],
        citations: [
          ...LCMC_ENT_PHYSICIAN_CITATIONS,
          {
            title: LCMC_WJMC_LOCATION_NAME,
            href: '/Our-Locations/West-Jefferson-Medical-Center',
            kbId: 'LOC',
            excerpt: 'Marrero hospital campus.',
          },
          {
            title: 'Ears, Nose and Throat Care',
            href: '/Our-Services/Ears-Nose-and-Throat-Care',
            kbId: 'SVC',
            excerpt: 'System ENT / otolaryngology hub.',
          },
        ],
        learnMoreHref: LCMC_DEMO_MOREAU_SICK_HREF,
        learnMoreLabel: 'Book an ENT visit',
      },
    },
    {
      id: 'west-jefferson',
      matchAny: [['west', 'jefferson'], ['wjmc'], ['marrero'], ['jefferson', 'clinic']],
      insight: {
        id: 'ai-lcmc-wjmc',
        headline: 'West Jefferson is the Marrero hospital campus',
        answer:
          'West Jefferson Medical Clinic searches should land on West Jefferson Medical Center. ENT demos continue to Gabrielle Moreau and the WJMC ENT service pages.',
        bullets: [
          'Hospital page: West Jefferson Medical Center.',
          'ENT physicians: Gabrielle Moreau, MD and Dominic Lirette, MD.',
        ],
        citations: [
          ...LCMC_ENT_PHYSICIAN_CITATIONS,
          {
            title: LCMC_WJMC_LOCATION_NAME,
            href: '/Our-Locations/West-Jefferson-Medical-Center',
            kbId: 'LOC',
            excerpt: 'LCMC Health hospital in Marrero.',
          },
          {
            title: 'ENT care at West Jefferson',
            href: '/West-Jefferson-Medical-Center/Our-Services/Ears-Nose-and-Throat-Care',
            kbId: 'SVC',
            excerpt: 'Campus ENT programs.',
          },
        ],
        learnMoreHref: '/Our-Locations/West-Jefferson-Medical-Center',
        learnMoreLabel: 'Open West Jefferson',
      },
    },
    {
      id: 'find-provider',
      matchAny: [['doctor'], ['physician'], ['provider'], ['specialist'], ['find', 'provider']],
      insight: {
        id: 'ai-lcmc-provider',
        headline: 'Use Find a Provider, then book',
        answer:
          'Physician searches use the same published catalog as Pulse. For ENT near West Jefferson, open Gabrielle Moreau then Patient Appointments.',
        bullets: [
          'Find a Provider is the directory hub.',
          'ENT demo doctor is Gabrielle Moreau, MD at WJMC.',
        ],
        citations: [
          ...LCMC_ENT_PHYSICIAN_CITATIONS,
          {
            title: 'Find a Provider',
            href: '/Find-a-Provider',
            kbId: 'HUB',
            excerpt: 'Published LCMC Health physicians.',
          },
        ],
        learnMoreHref: '/Find-a-Provider',
        learnMoreLabel: 'Find a provider',
      },
    },
    {
      id: 'book-appointment',
      matchAny: [['appointment'], ['book'], ['schedule'], ['cita']],
      insight: {
        id: 'ai-lcmc-book',
        headline: 'Patient Appointments can skip visit type',
        answer:
          'Booking searches should open Patient Appointments. ENT demos deep-link sick visit, West Jefferson, and Gabrielle Moreau so the visitor lands on time slots.',
        bullets: ['Add visit=sick-visit plus specialty, location, and provider on the URL.'],
        citations: [
          {
            title: 'Patient Appointments',
            href: LCMC_DEMO_MOREAU_SICK_HREF,
            kbId: 'PAGE',
            excerpt: 'Scheduler with ENT / WJMC / Moreau pre-selected.',
          },
        ],
        learnMoreHref: LCMC_DEMO_MOREAU_SICK_HREF,
        learnMoreLabel: 'Start booking',
      },
    },
  ],
  copy: {
    kicker: 'LCMC Health search',
    headingEmpty: 'Find a provider, location, or service',
    intro:
      'Search the way patients ask: start with ENT, a hospital (West Jefferson), or a doctor, then book from Patient Appointments.',
    placeholder: 'Search ENT, West Jefferson, Gabrielle Moreau…',
    emptyHint: 'Try “ENT West Jefferson,” “sinus specialist,” or “Gabrielle Moreau.”',
    resultsHint: ' — try ENT, a hospital name, or a physician',
    aiHeading: 'Care-aware guidance',
    citationsHeading: 'Recommended pages',
    facetLob: 'Content type',
    facetPeril: 'Focus',
    facetTopic: 'Topic',
    tips: [],
  },
  ctaByLob: {
    providers: 'View provider',
    locations: 'View location',
    ent: 'Explore ENT care',
    services: 'View service',
    appointments: 'Book a visit',
  },
  defaultCta: 'Open page',
  iconByLob: {
    providers: Stethoscope,
    locations: Building2,
    ent: Ear,
    services: HeartPulse,
    appointments: CalendarCheck,
  },
  featuredLob: 'ent',
  enableDemoPersona: false,
};
