import { Briefcase, Factory, FileText, Layers, Wrench } from 'lucide-react';

import type { SearchResultItem, SearchSitePack } from './types';

function item(partial: SearchResultItem): SearchResultItem {
  return partial;
}

const catalog: SearchResultItem[] = [
  item({
    id: 'qnx-super-spacer',
    kbId: 'PDP',
    title: 'Super Spacer',
    subtitle: 'Warm-edge insulating glass spacer',
    description:
      'Dual-seal Super Spacer for residential and commercial IG units. Helps improve thermal performance at the edge of glass while supporting durable, high-volume production.',
    href: '/Products/Insulating Glass Spacers/Super Spacer',
    lob: 'product',
    perils: ['igSpacers'],
    topics: ['residential', 'commercial', 'architects'],
    searchBuckets: ['spacer', 'ig', 'warmedge', 'window'],
    breadcrumb: ['Products', 'Insulating Glass Spacers', 'Super Spacer'],
    matchTerms: ['super spacer', 'warm edge', 'ig spacer', 'insulating glass', 'dual seal'],
    isNew: true,
  }),
  item({
    id: 'qnx-duralite',
    kbId: 'PDP',
    title: 'Duralite',
    subtitle: 'Single-seal warm-edge spacer',
    description:
      'Duralite warm-edge spacers for insulating glass where a single-seal system is specified. Built for consistent application and long-term IG durability.',
    href: '/Products/Insulating Glass Spacers/Duralite',
    lob: 'product',
    perils: ['igSpacers'],
    topics: ['residential', 'commercial'],
    searchBuckets: ['spacer', 'ig', 'warmedge', 'window'],
    breadcrumb: ['Products', 'Insulating Glass Spacers', 'Duralite'],
    matchTerms: ['duralite', 'single seal', 'warm edge', 'ig'],
  }),
  item({
    id: 'qnx-super-spacer-premium',
    kbId: 'PDP',
    title: 'Super Spacer Premium',
    subtitle: 'Premium dual-seal spacer',
    description:
      'Super Spacer Premium extends the Super Spacer platform for demanding IG specifications—thermal edge performance with a premium finish for architectural glass.',
    href: '/Products/Insulating Glass Spacers/Super Spacer Premium',
    lob: 'product',
    perils: ['igSpacers'],
    topics: ['commercial', 'architects'],
    searchBuckets: ['spacer', 'ig', 'warmedge', 'architect'],
    breadcrumb: ['Products', 'Insulating Glass Spacers', 'Super Spacer Premium'],
    matchTerms: ['super spacer premium', 'architectural', 'warm edge'],
  }),
  item({
    id: 'qnx-qlon',
    kbId: 'PDP',
    title: 'Q-LON Weatherseals',
    subtitle: 'Fenestration weatherseals',
    description:
      'Q-LON pile and foam weatherseals for windows and doors. Helps reduce air and water infiltration while supporting energy-efficient fenestration packages.',
    href: '/Products/Weatherseals/Q-LON Weatherseals',
    lob: 'product',
    perils: ['weatherseals'],
    topics: ['residential', 'commercial'],
    searchBuckets: ['weatherseal', 'window', 'door', 'energy'],
    breadcrumb: ['Products', 'Weatherseals', 'Q-LON Weatherseals'],
    matchTerms: ['q-lon', 'qlon', 'weatherseal', 'pile', 'door sweep', 'air infiltration'],
    isNew: true,
  }),
  item({
    id: 'qnx-mikron-7200',
    kbId: 'PDP',
    title: 'Mikron 7200 Sound Control System',
    subtitle: 'Commercial vinyl window profiles',
    description:
      'Mikron 7200 acoustic vinyl framing for commercial fenestration. Multi-chamber profiles designed to help reduce exterior noise on demanding sites.',
    href: '/Products/Extruded Solutions/Mikron 7200 Sound Control System',
    lob: 'product',
    perils: ['extrusion'],
    topics: ['commercial', 'architects'],
    searchBuckets: ['extrusion', 'window', 'commercial', 'vinyl'],
    breadcrumb: ['Products', 'Extruded Solutions', 'Mikron 7200 Sound Control System'],
    matchTerms: ['mikron', '7200', 'sound control', 'acoustic', 'vinyl', 'profile'],
  }),
  item({
    id: 'qnx-ig-spacers-hub',
    kbId: 'HUB',
    title: 'Insulating Glass Spacers',
    subtitle: 'Product category',
    description:
      'Compare Quanex warm-edge spacer platforms for residential and commercial insulating glass—including Super Spacer and Duralite families.',
    href: '/Products/Insulating Glass Spacers',
    lob: 'product',
    perils: ['igSpacers'],
    topics: ['residential', 'commercial', 'architects'],
    searchBuckets: ['spacer', 'ig', 'warmedge'],
    breadcrumb: ['Products', 'Insulating Glass Spacers'],
    matchTerms: ['ig spacers', 'warm-edge', 'insulating glass spacers'],
  }),
  item({
    id: 'qnx-weatherseals-hub',
    kbId: 'HUB',
    title: 'Weatherseals',
    subtitle: 'Product category',
    description:
      'Fenestration weatherseals and pile systems for windows and doors—including Q-LON and related sealing solutions.',
    href: '/Products/Weatherseals',
    lob: 'product',
    perils: ['weatherseals'],
    topics: ['residential', 'commercial'],
    searchBuckets: ['weatherseal', 'window', 'door'],
    breadcrumb: ['Products', 'Weatherseals'],
    matchTerms: ['weatherseals', 'seals', 'pile weatherseal'],
  }),
  item({
    id: 'qnx-hardware',
    kbId: 'HUB',
    title: 'Hardware Solutions',
    subtitle: 'Window and door hardware',
    description:
      'Hardware solutions for fenestration programs—operators, locks, and related components that pair with Quanex sealing and extrusion systems.',
    href: '/Products/Hardware Solutions',
    lob: 'product',
    perils: ['hardware'],
    topics: ['residential', 'commercial'],
    searchBuckets: ['hardware', 'window', 'door'],
    breadcrumb: ['Products', 'Hardware Solutions'],
    matchTerms: ['hardware', 'hinge', 'lock', 'operator'],
  }),
  item({
    id: 'qnx-access',
    kbId: 'HUB',
    title: 'Access Solutions',
    subtitle: 'Screens and access products',
    description:
      'Access and screening products for residential openings, including security screens and related fenestration accessories.',
    href: '/Products/Access Solutions',
    lob: 'product',
    perils: ['access'],
    topics: ['residential'],
    searchBuckets: ['screen', 'access', 'security'],
    breadcrumb: ['Products', 'Access Solutions'],
    matchTerms: ['access', 'security screens', 'screens'],
  }),
  item({
    id: 'qnx-wood',
    kbId: 'HUB',
    title: 'Wood Solutions',
    subtitle: 'Engineered wood components',
    description:
      'Engineered wood and millwork components for cabinet, window, and door manufacturers that need consistent supply and performance.',
    href: '/Products/Wood Solutions',
    lob: 'product',
    perils: ['wood'],
    topics: ['manufacturing'],
    searchBuckets: ['wood', 'millwork', 'cabinet'],
    breadcrumb: ['Products', 'Wood Solutions'],
    matchTerms: ['wood', 'millwork', 'engineered wood', 'cabinet'],
  }),
  item({
    id: 'qnx-mixing',
    kbId: 'HUB',
    title: 'Mixing Solutions',
    subtitle: 'Custom polymer mixing',
    description:
      'Custom mixing and polymer compounding for manufacturers that need formulated materials alongside extrusion and sealing programs.',
    href: '/Products/Mixing Solutions',
    lob: 'product',
    perils: ['mixing'],
    topics: ['manufacturing'],
    searchBuckets: ['polymer', 'mixing', 'compound'],
    breadcrumb: ['Products', 'Mixing Solutions'],
    matchTerms: ['mixing', 'compounding', 'polymer', 'custom mix'],
  }),
  item({
    id: 'qnx-solar',
    kbId: 'HUB',
    title: 'Solar Panel Components',
    subtitle: 'Residential solar components',
    description:
      'Component solutions for solar panel assemblies—part of Quanex’s broader materials and extrusion offering for energy applications.',
    href: '/Products/Residential/Solar Panel Components',
    lob: 'product',
    perils: ['solar'],
    topics: ['residential'],
    searchBuckets: ['solar', 'energy'],
    breadcrumb: ['Products', 'Residential', 'Solar Panel Components'],
    matchTerms: ['solar', 'panel', 'photovoltaic'],
  }),
  item({
    id: 'qnx-architects-warm-edge',
    kbId: 'HUB',
    title: 'Warm-Edge Spacers for Architects',
    subtitle: 'Specification resources',
    description:
      'Architect-facing guidance for specifying warm-edge spacers in commercial window and curtain-wall packages.',
    href: '/Products/For Architects/Warm-Edge Spacers',
    lob: 'resource',
    perils: ['igSpacers'],
    topics: ['architects', 'commercial'],
    searchBuckets: ['architect', 'warmedge', 'spacer', 'spec'],
    breadcrumb: ['Products', 'For Architects', 'Warm-Edge Spacers'],
    matchTerms: ['architect', 'specification', 'csi', 'warm-edge spacers'],
  }),
  item({
    id: 'qnx-commercial-systems',
    kbId: 'HUB',
    title: 'Commercial Window & Door Systems',
    subtitle: 'For architects',
    description:
      'Commercial fenestration systems and vinyl profiles for architectural projects—including acoustic and high-performance packages.',
    href: '/Products/For Architects/Commercial Window and Door Systems',
    lob: 'resource',
    perils: ['extrusion'],
    topics: ['architects', 'commercial'],
    searchBuckets: ['commercial', 'architect', 'window'],
    breadcrumb: ['Products', 'For Architects', 'Commercial Window & Door Systems'],
    matchTerms: ['commercial window', 'door systems', 'architects'],
  }),
  item({
    id: 'qnx-cap-extrusion',
    kbId: 'CAP',
    title: 'Extrusion Capabilities',
    subtitle: 'Manufacturing capability',
    description:
      'Precision polymer extrusion for window, door, and industrial profiles—from tool design through high-volume production.',
    href: '/Capabilities/Extrusion Capabilities',
    lob: 'capability',
    perils: ['extrusion'],
    topics: ['manufacturing'],
    searchBuckets: ['extrusion', 'polymer', 'manufacturing'],
    breadcrumb: ['Capabilities', 'Extrusion Capabilities'],
    matchTerms: ['extrusion', 'profile', 'die', 'polymer extrusion'],
    isNew: true,
  }),
  item({
    id: 'qnx-cap-polymer',
    kbId: 'CAP',
    title: 'Polymer Solutions',
    subtitle: 'Materials science',
    description:
      'Formulated polymer solutions that support sealing, extrusion, and custom mixing programs across Quanex manufacturing sites.',
    href: '/Capabilities/Polymer Solutions',
    lob: 'capability',
    perils: ['mixing'],
    topics: ['manufacturing'],
    searchBuckets: ['polymer', 'mixing', 'manufacturing'],
    breadcrumb: ['Capabilities', 'Polymer Solutions'],
    matchTerms: ['polymer', 'compound', 'material science'],
  }),
  item({
    id: 'qnx-cap-roll-forming',
    kbId: 'CAP',
    title: 'Roll Forming',
    subtitle: 'Metal forming',
    description:
      'Roll forming capabilities for structural and decorative metal components used in fenestration and related assemblies.',
    href: '/Capabilities/Roll Forming',
    lob: 'capability',
    perils: ['extrusion'],
    topics: ['manufacturing'],
    searchBuckets: ['manufacturing', 'extrusion'],
    breadcrumb: ['Capabilities', 'Roll Forming'],
    matchTerms: ['roll forming', 'metal', 'rolltrusion'],
  }),
  item({
    id: 'qnx-cap-engineered-wood',
    kbId: 'CAP',
    title: 'Engineered Wood',
    subtitle: 'Wood capability',
    description:
      'Engineered wood capability for millwork and cabinet components—consistent supply for OEM manufacturing partners.',
    href: '/Capabilities/Engineered Wood',
    lob: 'capability',
    perils: ['wood'],
    topics: ['manufacturing'],
    searchBuckets: ['wood', 'millwork', 'cabinet'],
    breadcrumb: ['Capabilities', 'Engineered Wood'],
    matchTerms: ['engineered wood', 'hardwood', 'residues'],
  }),
  item({
    id: 'qnx-equipment',
    kbId: 'SUPPORT',
    title: 'IG Equipment',
    subtitle: 'Plant equipment',
    description:
      'Secondary sealing equipment, high-speed automation, semi-automated IG lines, and manual spacer application support.',
    href: '/Service and Support/Equipment',
    lob: 'support',
    perils: ['igSpacers'],
    topics: ['manufacturing', 'service'],
    searchBuckets: ['equipment', 'ig', 'plant', 'line'],
    breadcrumb: ['Service and Support', 'Equipment'],
    matchTerms: ['equipment', 'ig line', 'automation', 'spacer application', 'plant'],
    isNew: true,
  }),
  item({
    id: 'qnx-line-layouts',
    kbId: 'SUPPORT',
    title: 'Line Layouts',
    subtitle: 'Plant planning',
    description:
      'IG line layout planning to help plants place spacer application, sealing, and finishing equipment for throughput.',
    href: '/Service and Support/Equipment/Line Layouts',
    lob: 'support',
    perils: ['igSpacers'],
    topics: ['manufacturing', 'service'],
    searchBuckets: ['equipment', 'plant', 'line', 'ig'],
    breadcrumb: ['Service and Support', 'Equipment', 'Line Layouts'],
    matchTerms: ['line layout', 'plant layout', 'throughput'],
  }),
  item({
    id: 'qnx-plant-transform',
    kbId: 'SUPPORT',
    title: 'Plant Transformation',
    subtitle: 'Operations support',
    description:
      'Plant transformation programs that combine equipment, process, and materials expertise to modernize IG manufacturing.',
    href: '/Service and Support/Plant Transformation',
    lob: 'support',
    perils: ['igSpacers'],
    topics: ['manufacturing', 'service'],
    searchBuckets: ['plant', 'equipment', 'manufacturing'],
    breadcrumb: ['Service and Support', 'Plant Transformation'],
    matchTerms: ['plant transformation', 'modernize', 'ig plant'],
  }),
  item({
    id: 'qnx-account-mgmt',
    kbId: 'SUPPORT',
    title: 'Account Management',
    subtitle: 'Customer support',
    description:
      'Dedicated account management for OEM partners—forecasting, quality, and application support across Quanex product lines.',
    href: '/Service and Support/Account Management',
    lob: 'support',
    perils: ['igSpacers'],
    topics: ['service'],
    searchBuckets: ['support', 'account'],
    breadcrumb: ['Service and Support', 'Account Management'],
    matchTerms: ['account manager', 'oem', 'customer support'],
  }),
  item({
    id: 'qnx-screens-plus',
    kbId: 'SUPPORT',
    title: 'Screens Plus',
    subtitle: 'Screening support',
    description:
      'Screens Plus support for security and insect screening programs, including replacement and OEM coordination.',
    href: '/Service and Support/Screens Plus',
    lob: 'support',
    perils: ['access'],
    topics: ['residential', 'service'],
    searchBuckets: ['screen', 'access', 'support'],
    breadcrumb: ['Service and Support', 'Screens Plus'],
    matchTerms: ['screens+', 'screens plus', 'security screen'],
  }),
  item({
    id: 'qnx-resources',
    kbId: 'PAGE',
    title: 'Resources',
    subtitle: 'Technical library',
    description:
      'Technical resources, literature, and continuing education materials for specifiers and manufacturing partners.',
    href: '/Resources',
    lob: 'resource',
    perils: ['igSpacers'],
    topics: ['architects', 'service'],
    searchBuckets: ['resource', 'spec', 'architect'],
    breadcrumb: ['Resources'],
    matchTerms: ['resources', 'literature', 'datasheet', 'white paper'],
  }),
  item({
    id: 'qnx-sustainability',
    kbId: 'PAGE',
    title: 'Sustainability',
    subtitle: 'Environmental commitment',
    description:
      'How Quanex approaches materials, energy performance, and responsible manufacturing across spacer, seal, and extrusion programs.',
    href: '/Sustainability',
    lob: 'page',
    perils: ['igSpacers'],
    topics: ['architects', 'commercial'],
    searchBuckets: ['energy', 'architect'],
    breadcrumb: ['Sustainability'],
    matchTerms: ['sustainability', 'esg', 'energy efficient', 'recycle'],
  }),
  item({
    id: 'qnx-careers',
    kbId: 'PAGE',
    title: 'Careers',
    subtitle: 'Join Quanex',
    description:
      'Openings across manufacturing, engineering, sales, and corporate functions. Explore how to build a career with Quanex.',
    href: '/Careers',
    lob: 'career',
    perils: ['igSpacers'],
    topics: ['service'],
    searchBuckets: ['career'],
    breadcrumb: ['Careers'],
    matchTerms: ['jobs', 'hiring', 'careers', 'openings'],
  }),
  item({
    id: 'qnx-contact',
    kbId: 'PAGE',
    title: 'Contact Us',
    subtitle: 'Talk to Quanex',
    description:
      'Reach a product specialist, request samples, or connect with account management for your plant or specification project.',
    href: '/Contact Us',
    lob: 'page',
    perils: ['igSpacers'],
    topics: ['service'],
    searchBuckets: ['support', 'account'],
    breadcrumb: ['Contact Us'],
    matchTerms: ['contact', 'sample', 'quote', 'representative'],
  }),
  item({
    id: 'qnx-locations',
    kbId: 'PAGE',
    title: 'Locations',
    subtitle: 'Manufacturing footprint',
    description:
      'Quanex manufacturing and support locations serving window, door, and IG customers.',
    href: '/Locations',
    lob: 'page',
    perils: ['igSpacers'],
    topics: ['manufacturing', 'service'],
    searchBuckets: ['support', 'manufacturing'],
    breadcrumb: ['Locations'],
    matchTerms: ['plant', 'location', 'facility', 'where we operate'],
  }),
];

export const quanexSearchPack: SearchSitePack = {
  siteName: 'quanex',
  brandName: 'Quanex',
  catalog,
  facetLabels: {
    lob: {
      product: 'Products',
      capability: 'Capabilities',
      support: 'Service & support',
      resource: 'Resources',
      career: 'Careers',
      page: 'Site pages',
    },
    peril: {
      igSpacers: 'Insulating glass spacers',
      weatherseals: 'Weatherseals',
      extrusion: 'Extruded solutions',
      hardware: 'Hardware',
      wood: 'Wood solutions',
      mixing: 'Mixing & polymers',
      solar: 'Solar components',
      access: 'Access & screens',
    },
    topic: {
      residential: 'Residential',
      commercial: 'Commercial',
      architects: 'Architects & specifiers',
      manufacturing: 'Manufacturing / OEM',
      service: 'Service partners',
    },
  },
  bucketSynonyms: {
    spacer: ['spacer', 'spacers', 'super spacer', 'duralite'],
    ig: ['insulating glass', 'ig unit', 'ig ', ' dual seal', 'single seal'],
    warmedge: ['warm edge', 'warm-edge', 'warmedge', 'edge of glass'],
    weatherseal: ['weatherseal', 'weatherseals', 'q-lon', 'qlon', 'pile', 'door sweep'],
    window: ['window', 'fenestration', 'sash', 'glazing'],
    door: ['door', 'entry door', 'patio'],
    extrusion: ['extrusion', 'extruded', 'mikron', 'vinyl profile', 'profile'],
    polymer: ['polymer', 'compound', 'mixing'],
    hardware: ['hardware', 'hinge', 'lock', 'operator'],
    wood: ['wood', 'millwork', 'cabinet'],
    mixing: ['mixing', 'custom mix', 'compounding'],
    solar: ['solar', 'photovoltaic', 'pv '],
    screen: ['screen', 'screens', 'security screen'],
    access: ['access', 'security screens'],
    commercial: ['commercial', 'architectural', 'curtain wall'],
    architect: ['architect', 'specifier', 'specification', 'csi'],
    equipment: ['equipment', 'machinery', 'automation'],
    plant: ['plant', 'factory', 'line layout', 'transformation'],
    line: ['line layout', 'ig line', 'production line'],
    energy: ['energy', 'thermal', 'u-factor', 'acoustic', 'sound'],
    vinyl: ['vinyl', 'pvc', 'mikron'],
    millwork: ['millwork', 'moulding'],
    cabinet: ['cabinet', 'kitchen'],
    compound: ['compound', 'formulation'],
    spec: ['spec', 'datasheet', 'literature', 'ce'],
    resource: ['resource', 'download', 'technical'],
    support: ['support', 'service', 'account'],
    account: ['account management', 'oem', 'customer'],
    career: ['career', 'job', 'jobs', 'hiring', 'opening'],
    manufacturing: ['manufacturing', 'oem', 'production'],
  },
  popularSearches: [
    'Warm-edge spacers for residential IG',
    'Super Spacer vs Duralite',
    'Q-LON weatherseals for windows and doors',
    'Mikron commercial vinyl systems',
    'IG line equipment and plant layout',
    'Extrusion and polymer capabilities',
  ],
  insightRules: [
    {
      id: 'ig-spacers',
      matchAny: [
        ['warm', 'edge'],
        ['insulating', 'glass'],
        ['ig', 'spacer'],
        ['super', 'spacer'],
        ['duralite'],
        ['spacer'],
      ],
      insight: {
        id: 'ai-ig-spacers',
        headline: 'Start with the IG spacer, then the plant',
        answer:
          'Quanex search is built around how IG is actually specified and produced. Warm-edge spacer choice (Super Spacer vs Duralite) drives thermal performance; equipment and line layouts determine whether that spec can run at volume.',
        bullets: [
          'Compare Super Spacer and Duralite on the Insulating Glass Spacers hub.',
          'Architects should open Warm-Edge Spacers for specification language.',
          'Plant teams should continue to Equipment and Line Layouts.',
        ],
        citations: [
          {
            title: 'Super Spacer',
            href: '/Products/Insulating Glass Spacers/Super Spacer',
            kbId: 'PDP',
            excerpt: 'Dual-seal warm-edge spacer for residential and commercial IG.',
          },
          {
            title: 'IG Equipment',
            href: '/Service and Support/Equipment',
            kbId: 'SUPPORT',
            excerpt: 'Automation and spacer application equipment for IG plants.',
          },
        ],
        learnMoreHref: '/Products/Insulating Glass Spacers',
        learnMoreLabel: 'Browse insulating glass spacers',
      },
    },
    {
      id: 'weatherseals',
      matchAny: [['weatherseal'], ['q-lon'], ['qlon'], ['pile'], ['door', 'sweep']],
      insight: {
        id: 'ai-weatherseals',
        headline: 'Seal the opening, not just the glass',
        answer:
          'Q-LON weatherseals complement warm-edge IG. If the ask is air/water infiltration, start with weatherseals; if it is U-factor at the glass edge, start with spacers.',
        bullets: [
          'Open Q-LON Weatherseals for pile and foam sealing systems.',
          'Pair with Hardware Solutions when the demo needs a full opening story.',
        ],
        citations: [
          {
            title: 'Q-LON Weatherseals',
            href: '/Products/Weatherseals/Q-LON Weatherseals',
            kbId: 'PDP',
            excerpt: 'Fenestration weatherseals for windows and doors.',
          },
          {
            title: 'Weatherseals',
            href: '/Products/Weatherseals',
            kbId: 'HUB',
            excerpt: 'Category hub for sealing systems.',
          },
        ],
        learnMoreHref: '/Products/Weatherseals',
        learnMoreLabel: 'Browse weatherseals',
      },
    },
    {
      id: 'extrusion',
      matchAny: [['mikron'], ['extrusion'], ['vinyl', 'profile'], ['sound', 'control'], ['polymer']],
      insight: {
        id: 'ai-extrusion',
        headline: 'Profiles plus materials science',
        answer:
          'Commercial vinyl stories land on Mikron extruded systems. Manufacturing partners who need the “how we make it” path should continue to Extrusion Capabilities and Polymer Solutions.',
        bullets: [
          'Mikron 7200 is the acoustic commercial profile example.',
          'Extrusion Capabilities and Polymer Solutions explain the plant-side offer.',
        ],
        citations: [
          {
            title: 'Mikron 7200 Sound Control System',
            href: '/Products/Extruded Solutions/Mikron 7200 Sound Control System',
            kbId: 'PDP',
            excerpt: 'Commercial vinyl framing for acoustic fenestration.',
          },
          {
            title: 'Extrusion Capabilities',
            href: '/Capabilities/Extrusion Capabilities',
            kbId: 'CAP',
            excerpt: 'High-volume polymer extrusion for OEM partners.',
          },
        ],
        learnMoreHref: '/Capabilities/Extrusion Capabilities',
        learnMoreLabel: 'See extrusion capabilities',
      },
    },
    {
      id: 'plant-equipment',
      matchAny: [
        ['equipment'],
        ['plant'],
        ['line', 'layout'],
        ['ig', 'line'],
        ['automation'],
      ],
      insight: {
        id: 'ai-plant',
        headline: 'From spacer spec to IG throughput',
        answer:
          'When the visitor is a plant engineer, route them to equipment first, then line layouts and plant transformation. Product PDPs still matter—they are what the line is built to run.',
        bullets: [
          'Equipment covers automation vs manual spacer application.',
          'Line Layouts and Plant Transformation support the operations conversation.',
        ],
        citations: [
          {
            title: 'IG Equipment',
            href: '/Service and Support/Equipment',
            kbId: 'SUPPORT',
            excerpt: 'Sealing equipment and IG automation.',
          },
          {
            title: 'Line Layouts',
            href: '/Service and Support/Equipment/Line Layouts',
            kbId: 'SUPPORT',
            excerpt: 'Plan spacer and sealing equipment on the plant floor.',
          },
        ],
        learnMoreHref: '/Service and Support/Equipment',
        learnMoreLabel: 'Open equipment support',
      },
    },
    {
      id: 'architects',
      matchAny: [['architect'], ['specif'], ['commercial', 'window'], ['curtain']],
      insight: {
        id: 'ai-architects',
        headline: 'Specify the edge, then the system',
        answer:
          'Architects typically need warm-edge spacer language plus a commercial system example. Keep product hubs and For Architects resources in the same result set.',
        bullets: [
          'Warm-Edge Spacers is the specification entry point.',
          'Commercial Window & Door Systems and Mikron 7200 show the assembled story.',
        ],
        citations: [
          {
            title: 'Warm-Edge Spacers for Architects',
            href: '/Products/For Architects/Warm-Edge Spacers',
            kbId: 'HUB',
            excerpt: 'Specifier guidance for warm-edge IG.',
          },
          {
            title: 'Commercial Window & Door Systems',
            href: '/Products/For Architects/Commercial Window and Door Systems',
            kbId: 'HUB',
            excerpt: 'Architectural fenestration systems.',
          },
        ],
        learnMoreHref: '/Products/For Architects/Warm-Edge Spacers',
        learnMoreLabel: 'Open architect resources',
      },
    },
  ],
  copy: {
    kicker: 'Quanex search',
    headingEmpty: 'Find products, capabilities & plant support',
    intro:
      'Search the way Quanex customers buy: start with the application (warm-edge IG, weatherseals, vinyl systems), then land on a product, a manufacturing capability, or the equipment that runs it.',
    placeholder: 'Search Super Spacer, weatherseals, extrusion, IG equipment…',
    emptyHint: 'Try “Super Spacer,” “Q-LON weatherseals,” or “IG line equipment.”',
    resultsHint: ' — try a starter search or describe the application',
    aiHeading: 'Application-aware guidance',
    citationsHeading: 'Recommended products & pages',
    facetLob: 'Content type',
    facetPeril: 'Solution area',
    facetTopic: 'Audience',
    tips: [
      {
        title: 'Search the application',
        body: 'Use “warm-edge spacer,” “weatherseal,” or “commercial vinyl” to land on the right product family.',
      },
      {
        title: 'Pair product with plant',
        body: 'IG specs and equipment live together—spacer PDPs plus Equipment / Line Layouts tell a complete OEM story.',
      },
      {
        title: 'Filter by who you are',
        body: 'Architects, residential OEMs, and plant engineers can refine by audience and solution area.',
      },
    ],
  },
  ctaByLob: {
    product: 'View product',
    capability: 'Explore capability',
    support: 'Open support',
    resource: 'View resource',
    career: 'View careers',
    page: 'Open page',
  },
  defaultCta: 'Open page',
  iconByLob: {
    product: Layers,
    capability: Factory,
    support: Wrench,
    resource: FileText,
    career: Briefcase,
    page: FileText,
  },
  featuredLob: 'product',
  enableDemoPersona: false,
};
