---
ID: "7c321c59-dc27-4589-8faf-d6ffcf511e11"
Parent: "dd708d7a-12c0-4c47-9811-31feb8fbb8fa"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/progressive/pkm/Presentation/Headless Variants/FAQListing/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260729T221144Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\emqWsGLKzRiKgWenEsIKMqdxvXhiQ4cT
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\emqWsGLKzRiKgWenEsIKMqdxvXhiQ4cT
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0a5ea23e-5d13-449e-b12f-f048f2037dae"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\emqWsGLKzRiKgWenEsIKMqdxvXhiQ4cT
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260729T221144Z
