---
ID: "95a9743d-0f6f-4921-a5f4-1e1f4c2ee0e5"
Parent: "f5b1abc7-c34a-437c-b38a-a7a93dd4cf0a"
Template: "f5b1abc7-c34a-437c-b38a-a7a93dd4cf0a"
Path: /sitecore/templates/Project/dfs/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F5B1ABC7-C34A-437C-B38A-A7A93DD4CF0A}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "dfd708cd-e0f8-4d6f-a7e7-9544b9471dae"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260819T163112Z
    - ID: "297acc19-e82a-47fe-b7f4-7e4df81dcc87"
      Hint: Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "52f0d45b-37ae-4f35-8a48-a73b59cf358f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mark.fronczak@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260819T163324Z
